### ISSUE TITLE
Insert User ID when submitting a form?

### ISSUE THREAD

**Issue by ScottPhillips** [CrestApps/laravel-code-generator#1]
If my table has a field user_id, is there a way to have Auth::user()->id inserted into the database when a user submits a form?

Thanks!

**Comment by CrestApps** [comment]
Hi, 
First of all thank you for using this package! Your feedback is highly appreciated to continue improving this package.

Updating fields should be handled either via the controller or using a observer class by hooking into the model events. It isn't something you'll get out of the box by default. However, I'll give it a thought to see if I can allow you to do that from the json string in future releases.

To handle that in the controller, you should be able to add this line in update and/or store action methods 

$data->user_id = Auth::user()->id;


Let me know if there is anything else I can help with.

**Comment by CrestApps** [comment]
v2.1.0 is finally out! This version has a property called `on-store` and other called `on-update` these two properties allow you to set the user Id automatically without having to manually update the controller. 
Feel free to upgrade to it and try it out. It is yet the most robust version out. Full improved documentation can be found at https://crestapps.com/laravel-code-generator/docs/2.1
