### ISSUE TITLE
Setting is-on-index:false in Artisan command sets as string, not boolean

### ISSUE THREAD

**Issue by 949mac** [CrestApps/laravel-code-generator#101]
### Environment:
- Laravel-Code-Generator Version: Latest as of 2019-01-12
- Laravel Version: 5.7

### Description:

Using `is-on-index:false` in Artisan comman prints `true` (via string conversion) in resource file.

### Steps/Commands To Reproduce:
![image](https://user-images.githubusercontent.com/23151962/51074896-857cb400-1639-11e9-89b8-5a59261f3172.png)

### Content Of The Resource-File:

![image](https://user-images.githubusercontent.com/23151962/51074903-9c230b00-1639-11e9-9ba5-20b8a34de26e.png)

**Comment by CrestApps** [comment]
Thank you for reporting this issue! This issue has been addressed and now part of the v2.2.13 release. Please upgrade your package to fix the issue
