### ISSUE TITLE
ErrorException :  compact(): Undefined variable: viewName

### ISSUE THREAD

**Issue by HAFVL007** [CrestApps/laravel-code-generator#102]
### Environment:
- Laravel-Code-Generator Version: 2.2
- Laravel Version: 5.7

### Description:
Error message when creating resources from existing database/table

### Steps/Commands To Reproduce:
php artisan create:resources Employee --with-migration --table-exists --force
The "employees.json" file was crafted successfully!
Scaffolding resources for employee...
A model was crafted successfully.

   ErrorException  : compact(): Undefined variable: viewName

  at C:\xampp\htdocs\crestapps\vendor\crestapps\laravel-code-generator\src\Commands\CreateControllerCommand.php:398
    394|             'template',
    395|             'controllerName',
    396|             'extends',
    397|             'withAuth',
  > 398|             'controllerDirectory'
    399|         );
    400|     }
    401|
    402|     /**

  Exception trace:

  1   compact("formRequestDirectory", "viewDirectory", "viewName", "modelName", "prefix", "perPage", "fileSnippet", "modelDirectory", "langFile", "fields", "withFormRequest", "formRequestName", "force", "resourceFile", "template", "controllerName", "extends", "withAuth", "controllerDirectory")
      C:\xampp\htdocs\crestapps\vendor\crestapps\laravel-code-generator\src\Commands\CreateControllerCommand.php:398

  2   CrestApps\CodeGenerator\Commands\CreateControllerCommand::getCommandInput()
      C:\xampp\htdocs\crestapps\vendor\crestapps\laravel-code-generator\src\Commands\CreateControllerCommand.php:86

  Please use the argument -v to see more details.

**Comment by CrestApps** [comment]
Thank you for reporting this issue! This issue has been addressed and now part of the v2.2.13 release. Please upgrade your package to fix the issue

**Comment by CrestApps** [comment]
Thank you for reporting this issue! This issue has been addressed and now part of the v2.2.13 release. Please upgrade your package to fix the issue
