### ISSUE TITLE
Error php artisan create:api-scaffold

### ISSUE THREAD

**Issue by diorz38** [CrestApps/laravel-code-generator#108]
### Environment:
- Laravel-Code-Generator Version: 2.3
- Laravel Version: 5.8.3

### Description:
When run command php artisan create:api-scaffold its return:
` The "model-extends" option does not exist.`

### Steps/Commands To Reproduce:
I follow Command in https://github.com/CrestApps/laravel-code-generator/tree/v2.3:

`php artisan create:scaffold Biography --with-migration --fields=id,name,age,biography,sport,gender,colors,is_retired,photo,range,month`

` php artisan create:api-resource Biography`
`php artisan create:api-scaffold Biography`
its return:
` The "model-extends" option does not exist.`

![crestapp-error](https://user-images.githubusercontent.com/4964821/54034667-14491f80-41ea-11e9-9f22-01e659faf89a.jpg)

![crestapp-error2](https://user-images.githubusercontent.com/4964821/54035346-c2a19480-41eb-11e9-8cf1-b3f6cda96c23.jpg)

### Content Of The Resource-File:

[biographies.zip](https://github.com/CrestApps/laravel-code-generator/files/2946228/biographies.zip)

**Comment by CrestApps** [comment]
Thank you for reporting this issue. Please upgrade to v2.3.1 to get the fix
