### ISSUE TITLE
 You must provide at least one field to generate the views!

### ISSUE THREAD

**Issue by ultimateakash** [CrestApps/laravel-code-generator#114]
### Before you submit an issue please read this
ultimate@ultimate-pc MINGW32 /c/xampp/htdocs/ultimateakash
$ php artisan resource-file:create AssetCategory --fields=id,name,description,is_active --translation-for=en,ar
The "asset_categories.json" file was crafted successfully!

ultimate@ultimate-pc MINGW32 /c/xampp/htdocs/ultimateakash
$ php artisan create:resources AssetCategory

   Exception  : You must provide at least one field to generate the views!

  at C:\xampp\htdocs\ultimateakash\vendor\crestapps\laravel-code-generator\src\C
ommands\CreateResourcesCommand.php:125

**Comment by CrestApps** [comment]
This issue should be fixed as of v2.3.2. Please upgrade to the new version and test drive it
