### ISSUE TITLE
Config files not created, nor template directory created, when running artisan publish

### ISSUE THREAD

**Issue by dougfelton** [CrestApps/laravel-code-generator#119]
### Environment:
- Laravel-Code-Generator Version: 2.3.2
- Laravel Version: 5.8.18

### Description:
On a fresh install of Laravel Code Generator the config file is not created in Laravel's config directory. Also, the template directory is not copied into the resources/laravel-code-generator directory. If I manually move those into their respective directories, the code generator generally works as expected.

### Steps/Commands To Reproduce:
1) Run composer require crestapps/laravel-code-generator --dev
2) Run php artisan vendor:publish --provider="CrestApps\CodeGenerator\CodeGeneratorServiceProvider" --tag=default

### Content Of The Resource-File:
N/A

**Comment by CrestApps** [comment]
in 2.3 you don't need to publish your resources unless you want to override the default template of config. If you want to publish the default template to modify it, please use the following command instead
```
php artisan vendor:publish --provider="CrestApps\CodeGenerator\CodeGeneratorServiceProvider" --tag=default-template
```
If you want to the config file use the following command
```
php artisan vendor:publish --provider="CrestApps\CodeGenerator\CodeGeneratorServiceProvider" --tag=config
```

Please let me know if that fix the issue

**Comment by redafillali** [comment]
you have to update the documentation for 2.4 version

**Comment by CrestApps** [comment]
@redafillali not yet. It’s on my todo list.  But been busy lately and can’t find time to work on it.

Most of the command are the same. I suggest you follow the 2.2 docs and read the change log from 2.4 to know what changed.  

For anyone interested in updating the docs, please reach out
