### ISSUE TITLE
Reserved word as method name [PHP < 7] 

### ISSUE THREAD

**Issue by essemme** [CrestApps/laravel-code-generator#12]
While updating through composer, "php artisan optimize" gave the error:

`syntax error, unexpected 'array' (T_ARRAY) in [..]/vendor/crestapps/laravel-code-generator/src/Commands/FieldsFileCreateCommand.php on line 136`

I renamed the "array" method to FieldTransformer::fieldsArray(), and it worked.
(I'm using PHP 5.6 at the moment, this is probably not a problem in PHP 7)

**Comment by CrestApps** [comment]
Thank you. Your commit have been merged.
