### ISSUE TITLE
How to edit the SQL statement that its getting the data from DB?

### ISSUE THREAD

**Issue by Rajaimaswadi** [CrestApps/laravel-code-generator#130]
Hello, i want to see the SQL statement that it communicate with the DB? i can not see it in Model, and SET and GET function are not all generated why?

Thanks!

**Comment by CrestApps** [comment]
Please review this [MysqlParser](https://github.com/CrestApps/laravel-code-generator/blob/master/src/DatabaseParsers/MysqlParser.php).
