### ISSUE TITLE
Install on Laravel 6.* 

### ISSUE THREAD

**Issue by mauphung** [CrestApps/laravel-code-generator#131]
Hi,
Is there any upgrade to use laravel-code-generator with existing Laravel 6.* version? How to make it with with version 2,2?
Thanks

**Comment by CrestApps** [comment]
Please upgrade to V2.4.0 which has support for Laravel 6+

**Comment by mauphung** [comment]
Please let me know where can I get V2.4.0

**Comment by CrestApps** [comment]
Update your package https://github.com/CrestApps/laravel-code-generator/releases
