### ISSUE TITLE
Cannot update V2.4.0 to Laravel 6.4.1

### ISSUE THREAD

**Issue by mauphung** [CrestApps/laravel-code-generator#132]
Hi,
I tried to install code generator V2.4.0 in my existing Laravel 6.4.1.
I added in composer.json file
"crestapps/laravel-code-generator": "^2.4.0"
Run php artisan update and get a following message:
C:\www\test>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Installation request for crestapps/laravel-code-generator ^2.4.0 -> satisfiable by crestapps/laravel-code-generator[v2.4.0].
    - crestapps/laravel-code-generator v2.4.0 requires laravel/framework ~5.1 -> satisfiable by laravel/framework[5.1.x-dev, 5.2.41,
...
 v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.5, v5.8.6, v5.8.7, v5.8.8, v5.8.9] but these conflict with your requirements or minimum-stability.

Would you please help me to install restapps/laravel-code-generator ^2.4.0 in my existing Laravel 6.4.1.
Thanks,
Mau

**Comment by CrestApps** [comment]
Please install version 2.4.1 instead.
