### ISSUE TITLE
Class 'CrestApps\CodeGenerator\HtmlGenerators\Str' not found

### ISSUE THREAD

**Issue by mauphung** [CrestApps/laravel-code-generator#134]
php artisan create:scaffold Singer –with-migration

C:\www\test>php artisan create:scaffold Singer --with-migration
Scaffolding web-based resources for singer...
A model was crafted successfully.
A controller was crafted successfully.
The routes were added successfully.
Crafting views...

   Symfony\Component\Debug\Exception\FatalThrowableError  : Class 'CrestApps\CodeGenerator\HtmlGenerators\Str' not found

  at C:\www\ACLmanager\vendor\crestapps\laravel-code-generator\src\HtmlGenerators\StandardHtml.php:281
    277|         $modelVariable = $this->getSingularVariable($this->modelName);
    278|         $valueString = 'null';
    279|
    280|         if (!is_null($value)) {
  > 281|             $valueString = Str::startsWith($value, '$') ? sprintf("%s", $value) : sprintf("'%s'", $value);
    282|         }
    283|
    284|         $defaultValueString = '[]';

**Comment by mauphung** [comment]
add use CrestApps\CodeGenerator\Support\Str; in  src\HtmlGenerators\StandardHtml.php. It's ok

**Comment by CrestApps** [comment]
I'll fix that and create a new release soon. Let me know if you encounter any new issues so I can make them part of the next release. 

Thank you
