### ISSUE TITLE
Strange paths when generating Controllers and FormRequests [MacOs]

### ISSUE THREAD

**Issue by essemme** [CrestApps/laravel-code-generator#15]
Using the command create:resources (or create:controller) I get the controller file in a Controllers inside an "App\Http" (that's the folder name, with the backslash) relative to the project's root; instead of app/Http/Controllers.

Form Requests ends up in Http/Requests under the project's root, not inside app/.
(working on the latest dev-master version, with published assets)

(Any suggestion on where to look to check the generation of these paths?)

**Comment by CrestApps** [comment]
Yayk!

The fix was in the `CreateFormRequestCommand.php` file. https://github.com/CrestApps/laravel-code-generator/commit/35f453e58d5205e70088733c8c9b22100805f11a#diff-99a112f463e2df8d4b56c87decc9b504

Please pull the last commit. You may also have to republish your view. Few things have been improved there.

**Comment by essemme** [comment]
Now, it seems that both Requests and Controllers end up inside the folder named "App\Http" 
(on mac - "\" is part of the folder name), instead of app/Http.
(I don't know if it's due to something specific to my project, or the mac filesystem)

**Comment by CrestApps** [comment]
Try the latest commit. That should fix that problem. you'll have to republish the view or update what you have. When you are using form-request, I moved some of the methods from the controller to the form-request.

**Comment by essemme** [comment]
Just a quick note to confirm, I have tried with the latest version (re-publishing assets and updating my custom templates), and it seems all right (no more path issues)

**Comment by CrestApps** [comment]
Thanks for your confirmation.
