### ISSUE TITLE
Unexpected '<<<<' in the generated controller.

### ISSUE THREAD

**Issue by ghosttk** [CrestApps/laravel-code-generator#152]
After generating a crud scaffold, in the Controller class, the moveFile function includes some unexpected characters.
Below is the generated function:
'
protected function moveFile($file)
    {
        if (!$file->isValid()) {
            return '';
        }
        
\<<<<<<< HEAD
        $path = config('codegenerator.files_upload_path', 'uploads');
\=======
        $path = config('laravel-code-generator.files_upload_path', 'uploads');
\>>>>>>> v2.3
        $saved = $file->store('public/' . $path, config('filesystems.default'));
 
        return substr($saved, 7);
    }
}
'

**Comment by diorz38** [comment]
yeah some minor github conflict issue, just delete two first row and 5th row, you good to go

**Comment by CrestApps** [comment]
Please use the latest version
