### ISSUE TITLE
ErrorException Undefined variable: name

### ISSUE THREAD

**Issue by AMG9980** [CrestApps/laravel-code-generator#174]
Hey I have a bug on php there is it the code : 
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\contact;

class ContactController extends Controller
{
    public  function NewContact()
    {
      $NewContact = New Contact();

      $NewContact->$name = "Amine Gharbi";

      $NewContact->$email = "amine.gharbi.1@esprit.tn";

      $NewContact->$message = "Bonjour voici un nouveau contact ";

      $NewContact->$Tel = "92775101";

      $NewContact->$Observation  = "En ligne";

      $NewContact->save();
    }
}

**Comment by CrestApps** [comment]
Guessing you just have a syntax error. your code should look like this "but this has nothing to do with the code generator

```
 $name = "Amine Gharbi"; 
$NewContact->email = "amine.gharbi.1@esprit.tn"; 
$NewContact->message = "Bonjour voici un nouveau contact "; 
$NewContact->Tel = "92775101"; 
$NewContact->Observation = "En ligne"; 
$NewContact->save();
```
