### ISSUE TITLE
Laravel 8 support

### ISSUE THREAD

**Issue by ehsantalkhouncheh** [CrestApps/laravel-code-generator#175]
- Laravel-Code-Generator Version:2.4.4
- Laravel Version: 8.55.0

### Description:

- the route that this package create is not compatible with laravel 8 requirment
- The model that create by this package use App namespace which is wrong for larael 8 and it should be App/Models
- Also it would be cool if views use Tailwind insted of bootstrap.

**Comment by CrestApps** [comment]
A new release was just published. Please try to use the latest release and let me know if you see any additional issues!
