### ISSUE TITLE
Class 'CrestApps\CodeGenerator\Traits\Str' not found

### ISSUE THREAD

**Issue by huszerldani** [CrestApps/laravel-code-generator#177]
### Environment:
- Laravel-Code-Generator Version: 2.4.5
- Laravel Version: 8.63.0

### Description:
I ran a command:
`php artisan resource-file:from-database User`

I got an error:
**Class 'CrestApps\CodeGenerator\Traits\Str' not found** at C:\laragon\www\dentit\vendor\crestapps\laravel-code-generator\src\Traits\Migration.php:119

### Fix
**I fixed it with importing Str class in Migration trait:**
vendor/crestapps/laravel-code-generator/src/Traits/Migration.php:8 --> **use CrestApps\CodeGenerator\Support\Str;**

**Comment by CrestApps** [comment]
Upgrade to v2.4.6.. that should work

**Comment by CrestApps** [comment]
Yes. It should work doe Laravel 5.1+

**Comment by marco-acorte** [comment]
> > Thank you for reporting this issues!
> > Upgrade to v2.4.6.. that should work
> 
> But does not work with Laravel 6.20

yes i't not working on a 6.x LTS project ... see my comment
https://github.com/CrestApps/laravel-code-generator/issues/178#issuecomment-981529628

**Comment by CrestApps** [comment]
@marco-acorte does it work with v2.4.7?

**Comment by marco-acorte** [comment]
> @marco-acorte does it work with v2.4.7?

Yes, it works perfectly
