### ISSUE TITLE
Live demo 2.0

### ISSUE THREAD

**Issue by qcol** [CrestApps/laravel-code-generator#18]
Is that exists?

![zaznaczenie_094](https://user-images.githubusercontent.com/358993/27429706-497895fe-5746-11e7-954a-da9d8b946017.png)

https://www.crestapps.com/laravel-code-generator/demos/2.0 <-- doesn't work

in DOC I found another working link, but for ver 1.2:
https://www.crestapps.com/laravel-code-generator/demos/1.2

**Comment by CrestApps** [comment]
Thank you very much for pointing this out.

v2.1 has been released and the demo for v2.1 is up and running.

**Comment by qcol** [comment]
thank You, 2.1 is awesome... but still bug in doc in links for demo:

![zaznaczenie_107](https://user-images.githubusercontent.com/358993/27827966-1286cad4-60ba-11e7-82cc-8b4d3ea2e073.png)

**Comment by CrestApps** [comment]
@qcol The link have been fixed.

I am glad you like v2.1. 

Thank you for paying attention to the details :)
