### ISSUE TITLE
Generate code without layouts and views.

### ISSUE THREAD

**Issue by mgip** [CrestApps/laravel-code-generator#183]
Hello guys, beforeall, thx so much for amazing package.

It's just a question:

I have implemented a dashboard html with a huge frontend resource, i want to know if i can generate except the layouts and view stuff...

could you show me how do that, or the documentation to this... i didn't find it.

Thanks.

**Comment by CrestApps** [comment]
I don’t know if you can create views without layout. But you maybe able to. Try passing empty string to `—layout` parameter when calling create view command

**Comment by mgip** [comment]
> I don’t know if you can create views without layout. But you maybe able to. Try passing empty string to `—layout` parameter when calling create view command

OK. but i figure out without layout statement, i mind, after create a resource-file, create the resource [model], that's it.

The problem i have now, is change the view path, i dont find how do i this.
