### ISSUE TITLE
Custom Folder

### ISSUE THREAD

**Issue by mgip** [CrestApps/laravel-code-generator#184]
Hello guys, beforeall, thx so much for amazing package.

Is any way to change the folder output to controllers, models, routesm etc etc.

Thanks.

**Comment by CrestApps** [comment]
Hello, you should be able to add the rules to the `laravel-code-generator.php` file

Here is a list of available config you can add to the file. 
https://github.com/CrestApps/laravel-code-generator/blob/master/config/default.php
