### ISSUE TITLE
Blog Post about CrestApps generator (and custom templates)

### ISSUE THREAD

**Issue by essemme** [CrestApps/laravel-code-generator#19]
Hello, just a note to let you know I wrote a blog post about my experience using Laravel Code Generator, with examples of adding custom features to the templates:

[Saving time with a CRUD generator for Laravel](https://stefanomanfredini.info/en/2017/06/saving-time-crud-generator-laravel/)

(Comments and suggestions welcome! 
Also, english is not my first language, so feel free to point out mistakes and typos)

**Comment by CrestApps** [comment]
Wow! This is great.
I am happy that your experience went very well. And thank you for taking time to write about your experience and use case.

I have couple of suggestions just to get this article up to date.
1) I recommend you pull the latest code from `dev-master`. The templates have slightly change as they become more robust out of he box. Some variables were changes others were added. You can even create your own variables if needed!
2) I suggest you write a small example about a basic use case without any integration. Many people like to know the out of the box example. Then they can read about integrating it with out her tools there.

Here is a short example that works in `dev-master` (version 2.1 should be released soon) 
```
php artisan fields-file:create AssetCategory --names=id,name,description,is_active
php artisan create:resources AssetCategory
```

PS: feel free to find my email in `composer.json` file and send me an email directly.

**Comment by essemme** [comment]
1. Great, this is useful! I'm busy yet, I'll wait for 2.1 stable (and the docs about the new custom variables feature :) )
2. Yes, good idea - maybe another (shorter) post for the intro.

I'll contact you by email if needed for details, etc.

**Comment by CrestApps** [comment]
v2.1.0 has been release. Full documentation, example, and live demo can be found at https://crestapps.com/laravel-code-generator/docs/2.1

I am closing this thread. Feel free to contact me directly via email.

Again, thank you for your continues contribution to this project!
