### ISSUE TITLE
Adding an archive when using soft deletes?

### ISSUE THREAD

**Issue by steveijar** [CrestApps/laravel-code-generator#191]
I've been looking at if I can add an archive page for soft deleted models, with a restore and force delete methods.

I've got something working by basically duplicating your work, the index view, amending the controller CreateControllerCommand and amending couple of the templates.

But before I start getting too deep I wanted to ask is there any reason why an archive page wouldn't work?

Is there any technical reason you didn't include it?

**Comment by MikeAlhayek** [comment]
I have not been using Laravel for many years. Is Archive a new feature Laravel provides?

**Comment by steveijar** [comment]
Hi Mike,
Sorry should have worded it better, its not a specific Laravel feature, I was just looking to add a new view that lists soft deleted records so they can be restored or force deleted.

I was hoping I could do something like, "if the flag --with-soft-delete has been used then add the 'archive' routes, views and methods" but I'm a relative new to Laravel so before I spend a long time trying to work out how to do it, I wanted to see if its something you have already tried and it didn't work or if there was some technical reason it wouldn't work!

If its not something you've tried then I'm happy to give it a go myself!

**Comment by MikeAlhayek** [comment]
It was never on the work scope. However, I am okay with introducing a new flag what would allow the user to soft-delete, include trash and when the record is deleted, we can show restore option. Feel free to submit a PR

**Comment by steveijar** [comment]
I shall give it go and see what I can do!

Great project BTW, I found it really useful while learning Laravel!
