### ISSUE TITLE
Generate from existing Models

### ISSUE THREAD

**Issue by MilesHart** [CrestApps/laravel-code-generator#192]
**Is your feature request related to a problem? Please describe.**
We have already mapped out our Models with relationships, we want something to generate the Controller and Views/Layout

**Describe the solution you'd like**
Could we add this option in the generate file?

**Describe alternatives you've considered**
The table names are not compiling to Laravel naming conventions.

**Additional context**
Unless there is a better approach.

**Comment by MikeAlhayek** [comment]
If the schema exists in a MySQL database, you can create the JSON file from there first. Then you can create you controller and views.

I don't remember, but I don't think there is an option to create from a model.
