### ISSUE TITLE
Suggestion: permissions

### ISSUE THREAD

**Issue by qcol** [CrestApps/laravel-code-generator#20]
Hi, how do you think about create:permissions command? It should build crud for any existing permission  package (edit/create roles, permissions). It is common task in many web apps.

**Comment by CrestApps** [comment]
Do you existing schema for roles, and permission?

**Comment by qcol** [comment]
depends what packege You choose.... spatie/laravel-permission? Zizaco/entrust?

**Comment by CrestApps** [comment]
The CodeGenerator allows you to create CRUD for anything as long as you know the fields. It is not the package responsibility to know the CRUD for all permission packages out there.


Lets say you want to create a resources/CRUD for a package that requires the following column id, name. you can create the resources/CRUD using the following command

php artisan fields-file:create Role --names=id,name
php artisan create:resources Role

The above commands assume you are using dev-master or v2.1+.

each package may required a different table schema/CRUD so you'll just create to create crud for the packages you are using.

Perhaps, you can create the CRUD using Laravel-Code-Generator and write a blog about it for others to use. :)

**Comment by qcol** [comment]
I mean creating permissions CRUD based on one of existing package out of the box, but you're right, everyone uses another package so can prepare own json file compatible with any permission package.
