### ISSUE TITLE
Need Dependant Select

### ISSUE THREAD

**Issue by kulkarniyudhi** [CrestApps/laravel-code-generator#204]
**Need Dependant Select **

If i have user crud with city & state how can i  select state then cities related to state will be populated by ajax.

Thank You.

**Comment by MikeAlhayek** [comment]
I am not sure we would want this complicated logic in the CRUD generator since it’s not a very common use case.

I would suggest locking the resource and add this custom code to your views instead of relaying in the code generator to create it for you.

**Comment by kulkarniyudhi** [comment]
Got It. Thank you for quick reply.
