### ISSUE TITLE
The file resources/codegenerator-files/pfx_countries.json was not found!

### ISSUE THREAD

**Issue by mohaghegh** [CrestApps/laravel-code-generator#22]
Hi
Thanks for this nice generator.

I'm using the Laravel Code generator to generate resources from my existing data tables.
this is the command:
`php artisan create:resources Country --table-name pfx_countries --table-exists`

But I get this exception:
`The file resources/codegenerator-files/pfx_countries.json was not found!`

It generates a file named countries.json in resource/codegenerator-files path.
Seems that `--table-name` parameter is not considered when naming the json fields file.

Best

**Comment by CrestApps** [comment]
Indeed it is a bug. The correct fields-file name is `countries.json` as it was generated for you.

The release `v2.1.3` fixes this issue. I recommend you upgrade to it.

As a workaround for the version you're on, run the follow commands
```
// This command will create fields-file called `countries.json` from your existing database (since you already have this file, you can skip this command)
php artisan create:fields-file Country --table-name=pfx_countries

//This command will use the  `countries.json` field to generate the resources 
php artisan create:resources Country
```
