### ISSUE TITLE
QUESTION: [feature request] New ways to define relationships 

### ISSUE THREAD

**Issue by essemme** [CrestApps/laravel-code-generator#3]
It's great to be able to define relationships through the models (and resources) generation command, but i find it not easy to do it through the shell when the models are complex, with many relationships. 

Is it possible to:
- add a way to (manually) define relationships directly in the fields definition json file
and / or
- automatically extrapolate the relations form an existing table - based on the names when tables / fields are following the naming conventions (or based on foreign key definitions in the database, whichever is easier to implement / maintain).

**Comment by essemme** [comment]
Well, it's not a big issue (it's very easy to edit the model classes to add the required relationships), it would be nice to have, if you plan to add relationships management in the generated controllers and views too (in the future, I know it's far from trivial).

I'm not even sure it's worth the time to implement it.. the package is already great at providing a fast way to generate boilerplate code, easy to edit and add to, while adding almost no dependency from third party code or imposing additional design patterns - such feature could be nice, but I understand that keeping it simple is the way to go.

**Comment by CrestApps** [comment]
I am glad you are bringing this up. Yes this package offer lots of neat code and get you a huge jump start. However, I am happy to inform you that all the point you mentioned above are on the road map. Additionally, most or all may be in the next release.

**Comment by essemme** [comment]
That's great!
This is the reason I'm using this package: a quick start of readable "standard" laravel code, ready to edit and build upon. Other admin panels or generators (I tried a couple) went a little too much in the way (imposing patterns like Repository and others, or their whole new way of doing things). 
They are good, no doubt, but were not a good fit for my current project needs. 
With CrestApps code generator I have no problems coding features like multi-language contents (managed with [Laravel Translatable](https://github.com/dimsav/laravel-translatable)) or integrating a template like [Laravel AdminLTE](https://github.com/jeroennoten/Laravel-AdminLTE) - just like any vanilla laravel "CRUD" application.
I'll stick with it, and add new issues/questions/comments here if needed.

**Comment by CrestApps** [comment]
Glad to know your using multiple languages in your project. Please let me know how that works for you. FWIW, when useing the `php artisan create:fields-file` or `php artisan create:resources ModelName --table-exists` you can utilize the `--translation-for=en,fr....` option to auto generate the locale files automatically which should save you lots of time :). The only thing is left for you will be to change the English title to other languages.

**Comment by essemme** [comment]
I need to use gettext (and poedit) for interface translation, so I'm not using this option (I see, another time saver). 
Not a problem, since it's easy to copy the "default" generator template folder, as suggested by your documentation, and edit views / controller stubs where needed (usually just surrounding the strings and messages with the _i() function).
I also added something (in model, controller, views stubs) to prepare for the multi language contents (adding some required bit to the model, and some logic to create / update / display translations for a single field (the somewhat standard "name"). Fully automating and integrating the Translatable package would be a lot harder and take quite longer; this way it's very quick to get started with a multi language ready CRUD panel, then code the additional logic.

**Comment by CrestApps** [comment]
@essemme relation handling should be part of the next release. Handling the relation has two major parts.
1. Create the relation in the model 
2. Use the relation each time the foreign key is accessed,

The first step was coded and it is now part of the `dev-master` version. Feel free to give it a try and leave me some feedback.

**Quick starting tips**
Any field with a name that end "_id" is considered a foreign key unless specified other wise. And every foreign-key will have a foreign-relation added to it's model. When creating the relations, any field with no specified relation, a `belongsTo` relation is created.

To flag a field with a name that ends with "_id" as not a foreign relation, you add the this line to the fields-file `"is-foreign-relation": false`.

Additionally, to specify the relation you want to create for each field, you'll need to add the following json code to the fields-file 

```
"foreign-relation": {
    "relation-name": "creator",
    "foreign-name": [
        "first_name",
        "middle_name",
        "last_name"
    ],
    "type": "belongsTo",
    "params": [
        "App\\Models\\User",
        "user_id",
        "id"
    ]
}
```
The above will create the following relations
```
    /**
     * Get the creator for this model.
     */
    public function creator()
    {
        return $this->belongsTo('App\Models\User','user_id','id')
    }
```
the entry `foreign-name` is not yet used, but will be used by part 2 of this feature to tell the code generator which foreign-column should be used to construct the title. In the above example, we will concatenate the field `first_name`, `middle_name` and `last_name` columns and display the user's full name as the creator. This should give the use a lot of flexibility on what to display.

If you used this feature while in dev, your feedback is highly appreciated.

**Comment by essemme** [comment]
This is great!
I'll try it as soon as possible

**Comment by CrestApps** [comment]
The current `dev-master` version should now fully handle the foreign relations. It should automatically add the relations to the model, and use the relation when needed. It should also create collections to populate the `select` menu with the options available in the database.

This feature is huge and saves tons of time for the end user. It is not yet complete but it is 90% there. When you use it, please share with me your experience to help me improve it.

To use it, you have to publish the new view. Multiple view have been changed.

**Comment by essemme** [comment]
Great!
I believe I'll be on it tomorrow.
I'll have to update my custom templates -and merge back a couple of changes from my fork- so maybe I'll do a parallel "vanilla" test using dev-master and the default template.

**Comment by CrestApps** [comment]
@essemme before you make any changes to your code, please use the package as is. it should contain everything you need without having to make a change.

If the `dev-master` is missing something for some reason please let me know.

**Comment by essemme** [comment]
Perfect.
Just a (really) quick test with "vanilla" settings and default templates - and it works.
The only thing I noticed is, the Id of the related model is displayed in views (index column, shown label for the relation select in form view, etc. - e.g. {{ $mymodel->RelatedModel->id }}). 
I don't know if it's relevant (didn't check the generators' code yet), I was using a custom "name" field, which I added in the codegenerator "common_header_names" config array.

Well, not a big problem, it's easy and quick to edit it in the resulting views. (Maybe is this in the roadmap for that missing 10% you were referring to?)

I'll check later with my "real world" project, merging my custom templates back in - so I'll test if there is everything I need to customize the templates (as per #8 )

**Comment by CrestApps** [comment]
When you generate the fields from existing database, there is no way for me to know which column should be used as display, so the safest route is to display the primary key. However, when the field's file is generated you can change that from the primary key to a column of your choose. Just open the generated fields file, under the `foreign-relation` change the `field` property to the name of the foreign field to display.

The missing 10% is for other things that I am still working on.

**Comment by essemme** [comment]
Oh yes, i was in a hurry and i skipped that. 
It' more than enough - automatically selecting the first matching field of the "common_header_names" config array would be just the icing on the cake. And, not needed - as tweaking the fields file and (re-)generating resources from it is super fast.

**Comment by CrestApps** [comment]
@essemme right, I am working on adding the icing on the cake. I have to add little more advance logic to make sure that field already exists on the foreign model before we use it.

With the current `dev-master` version, you are able to add `foreign-constraint` to the database migration from the fields-file like this
```
"foreign-constraint":{
            "field": "user_id",
            "references": "id",
            "on": "users",
            "on-delete":"cascade",
            "on-update":"cascade",
            "references-model": "App\\Models\\User"
        }
```

Additionally, if a foreign-constraint exists, a foreign-relation will automatically get added to the model. More to this is coming

**Comment by CrestApps** [comment]
This is not part of the `master-dev` branch. It will be part of the new 1.3.0 release. Please test the latest changed and let me know if you run into any issue. Lots of the code was changed.
Make sure you publish the latest templates and config file.
