### ISSUE TITLE
crestapps.com is down

### ISSUE THREAD

**Issue by jmallison** [CrestApps/laravel-code-generator#31]
### Description:
Every page on the website gives an HTTP 500 error.

### Steps/Commands To Reproduce:
Try to access any page on the site.

**Comment by CrestApps** [comment]
Sorry about that.  Working with the hosting company to fix the issue.   Horrible hosting company fastcomet.com

**Comment by jmallison** [comment]
No worries. Thanks for making this resource freely available! No need to apologize, ever!

**Comment by CrestApps** [comment]
It is back up! Got to move the site to a better hosting company
