### ISSUE TITLE
mysql 'bit' type is not mapped as 'boolean' in codegenerator.php config file

### ISSUE THREAD

**Issue by moumenz** [CrestApps/laravel-code-generator#37]
### Environment:
- Laravel-Code-Generator Version: 2.2.5
- Laravel Version: 5.5.22

### Description:
[Exception]
The type bit is not mapped in the 'eloquent_type_to_method' key in the config file.

### Steps/Commands To Reproduce:
php artisan resource-file:from-database Product --table-name=products

### Solution
add 'bit' => 'boolean', to config file

**Comment by CrestApps** [comment]
Added
