### ISSUE TITLE
--table-name= is totally ignored in the  generated model class, plural form is used instead

### ISSUE THREAD

**Issue by moumenz** [CrestApps/laravel-code-generator#38]
### Environment:
- Laravel-Code-Generator Version: 2.2.5
- Laravel Version: 5.5.22

### Description:
Illuminate \ Database \ QueryException (42S02)
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel55.attributesets' doesn't exist (SQL: select * from `attributesets` where `attributesets`.`id` in ())

### Steps/Commands To Reproduce:
go to : http://localhost/laravel55/public/attributesets (same as http://localhost/laravel55/public/products_cats) 

### Cause

- Method 1:

option: `--table-name=whatever` is totally ingnored when generating the model class using commands:
```
php artisan resource-file:from-database Mytable --table-name=whatever
php artisan create:resources Mytable
```
whatever we put in `--table-name=` ...., generated model always have `protected $table = <plural form of choosen model name>` (`'mytables'` in the above example).

#### Some examples:

```
php artisan resource-file:from-database Actor --table-name=whatever
php artisan create:resources Actor
```

**result  => `protected $table = 'actors';`**

```
php artisan resource-file:from-database Actress --table-name=whatever
php artisan create:resources Actress
```
**result => `protected $table = 'actresses';`**

- Method 2:

when using the single command, the result is **OK**:
`php artisan create:resources Mytable --table-exists --table-name=whatever`
**result => `protected $table = 'whatever';` // (as expected)**

**Comment by CrestApps** [comment]
I think something is wrong with your environment. I can't reproduce the issue on my end. Make sure you do the following. Since I made some fixes that could impact you, make sure you use the dev-master version instead of v2.2.5.

```
composer dump-autoload
php artisan vendor:publish --provider="CrestApps\CodeGenerator\CodeGeneratorServiceProvider" --tag=default --force
```
If you continue to have the same problem after that

**Comment by moumenz** [comment]
I was using the dev-master version.
```
composer remove  crestapps/laravel-code-generator
composer require crestapps/laravel-code-generator:dev-master --dev
composer dump-autoload
php artisan vendor:publish --provider="CrestApps\CodeGenerator\CodeGeneratorServiceProvider"
```
I got the version after your commit 4b90e4f (which causes isssue #39 that I fixed in my PR #40)
but I still having the same problem: 
```
php artisan resource-file:from-database Test --table-name=products
php artisan create:resources Test
```
gives me :` protected $table = 'tests';` instead of `protected $table = 'products';`

Please note that:

`php artisan create:resources Test --table-exists --table-name=products --force`
gives me the correct result: `protected $table = 'products';`

**Comment by CrestApps** [comment]
This is giving you the wrong table name in the model because your not telling the generator what the table name is. Instead of `php artisan create:resources Test` you should use `php artisan create:resources Test --table-name=products` This is not a bug rather the design.

```
// Here you are saying look for a table that is called "products" and create a resource file called "tests.json" 
php artisan resource-file:from-database Test --table-name=products

// Here we are saying generate the resource from the "tests.json" file, and make sure to generate the resource with "products" for a table name.
php artisan create:resources Test --table-name=products

```

**Comment by moumenz** [comment]
Thank you Mike,
I understand now the behaviour of create:resources command.
It looks only to the json file even with --table-name option: it will create the model class with the given table name even the table doesn't exisit. That's what confused me :)

**Comment by CrestApps** [comment]
Yes. I'll put it on the to do list to store the table name directly in the resource file in the future so that step is not needed.

Please use v2.2.6 instead of dev-master to prevent any future issue since the dev-master is not stable all the time.

**Comment by CrestApps** [comment]
The change  was implemented in `dev-master`. When you create resource-file from existing database, the table name is writes to the resource-file. So when you issue `php artisan create:resources` command you no longer need to pass the `--table-name` option each time.

**Comment by moumenz** [comment]
Good news. I will give it a try.
