### ISSUE TITLE
Are you planing to create api-resources as well?

### ISSUE THREAD

**Issue by matevisky** [CrestApps/laravel-code-generator#42]
It would be nice feature to add api-resource file as well during the scaffolding. If it is not a near future plan let me know, I will find the way to add it... Thx so far so good stuff!

**Comment by CrestApps** [comment]
Hi, 
Thank you for your choosing to use this package.
Creating code for an API with documentation is on the roadmap along with other cool stuff. Not sure about the time frame on that yet. It is very possible for that to be part of next release but no commitment yet.

**Comment by CrestApps** [comment]
Scaffolding an API is completed in the `v2.3` branch. https://github.com/CrestApps/laravel-code-generator/tree/v2.3

You should have the following new commands
```
php artisan create:api-controller
php artisan create:api-scaffold
php artisan create:routes --for-api
```
Also, if your using Laravel 5.5+, you can create [ApiResources](https://laravel.com/docs/5.5/eloquent-resources) using the following command
```
php artisan create:api-resource
```

This is a nice command to get you everything in one line
```
php artisan create:api-scaffold Test --with-form-request --with-api-resource --version=v1
```

Let me know if you run into any bugs.

**Comment by b0rt** [comment]
Hi there i did update to v2.3 branch and ran 
```
composer update
php artisan vendor:publish --provider="CrestApps\CodeGenerator\CodeGeneratorServiceProvider" --tag=default --force
```

but still get an error running:
```
php artisan create:api-scaffold Project --with-form-request --with-api-resource --api-version=v1
Scaffolding api-based resources for project...
The model already exists!

In Filesystem.php line 41:

  File does not exist at path /var/www/resources/laravel-code-generator/templates/default/api-resource.stub

```
 (Project is my Model with existing resources/laravel-code-generator/sources/projects.json)

other than wgetting the stubs, what should i do or investigate ?

thank you kindly, 
Stephan

**Comment by CrestApps** [comment]
@b0rt Since I have not put together an official documentation yet for v2.3, it is important for you to ready the [CHANGELOG.md
](https://github.com/CrestApps/laravel-code-generator/blob/v2.3/CHANGELOG.md) file. There are few changes to existing commands.

In v2.3 we cut down the installation process to 1 step. So publishing resources is no longer required. so you should delete all the default templates `/var/www/resources/laravel-code-generator/templates/default/` and `/var/www/resources/laravel-code-generator/templates/default-collective/` if exists. Additionally you should delete the `codegenerator.php` file from the config folder and then rename the codegenerator_custom.php file to laravel-code-generator.php

Here s what the changelog states
> - The user is no longer required to publish the default templates. This is much better step to prevent upgrade braking when the template are updated during a patch release. The user should publish templates only if he/she want to modify it and rename it. It is best to delete existing template and template-collective from the folders from the default publish path of your project.
> 
> - The user is no longer have to publish resource to install the package! One line only is required to install the package on laravel 5.5+ (i.e, composer require crestapps/laravel-code-generator --dev)
> 
> - IMPORTANT: delete the the codegenerator.php file from your config folder, then rename the codegenerator_custom.php file to laravel-code-generator.php. Alternatively, you can delete both codegenerator.php and codegenerator_custom.php

**Comment by CrestApps** [comment]
This request is fully implemented. 

You can now issue a commands like this

```
php artisan create:api-scaffold User --with-api-docs --api-version=v1
```

The previous command scaffold the api along with some documentations.

Alternatively, you can create the API-documents via a different command.
```
php artisan api-docs:scaffold User
```

Happy coding.

**Comment by CrestApps** [comment]
@b0rt if you continue to have that problem make sure you have the correct version in your composer.json file. Also, make sure you pull the latest code from GitHub to test the final product.

```
"crestapps/laravel-code-generator": "v2.3.x-dev",
```
