### ISSUE TITLE
Relations not created in resource file with  resource-file:create --relations

### ISSUE THREAD

**Issue by heingithub** [CrestApps/laravel-code-generator#44]
### Environment:
- Laravel-Code-Generator Version: 2.2
- Laravel Version: 5.5.31

### Description:
When generating a resource file the "--relations" parameter is ignored and no relation attributes are created.

### Steps/Commands To Reproduce:
php artisan resource-file:create Category       --force \
    --fields=id,name,description,is_verified,is_active \
    --translation-for=en,ar \
    --relations="name:items;type:hasMany;field:title;params=App\Models\Item|item_id|id,"

### Content Of The Resource-File:
categories.json -----

{
    "fields": [
        {
            "name": "id",
            "labels": {
                "en": "Id",
                "ar": "Id"
            },
            "html-type": "text",
            "css-class": "",
            "options": {},
            "html-value": null,
            "validation": "",
            "is-on-index": false,
            "is-on-show": false,
            "is-on-form": false,
            "data-type": "int",
            "data-type-params": [],
            "data-value": null,
            "is-index": false,
            "is-unique": false,
            "is-primary": true,
            "comment": null,
            "is-nullable": true,
            "is-header": false,
            "is-unsigned": true,
            "is-auto-increment": true,
            "is-inline-options": false,
            "is-date": false,
            "date-format": "",
            "cast-as": "",
            "placeholder": {
                "en": "Enter id here...",
                "ar": "Enter id here..."
            },
            "delimiter": "; ",
            "range": [],
            "foreign-relation": null,
            "foreign-constraint": null,
            "on-store": null,
            "on-update": null
        },
        {
            "name": "name",
            "labels": {
                "en": "Name",
                "ar": "Name"
            },
            "html-type": "text",
            "css-class": "",
            "options": {},
            "html-value": null,
            "validation": "string|min:1|max:255",
            "is-on-index": true,
            "is-on-show": true,
            "is-on-form": true,
            "data-type": "string",
            "data-type-params": [
                255
            ],
            "data-value": null,
            "is-index": false,
            "is-unique": false,
            "is-primary": false,
            "comment": null,
            "is-nullable": true,
            "is-header": true,
            "is-unsigned": false,
            "is-auto-increment": false,
            "is-inline-options": false,
            "is-date": false,
            "date-format": "",
            "cast-as": "",
            "placeholder": {
                "en": "Enter name here...",
                "ar": "Enter name here..."
            },
            "delimiter": "; ",
            "range": [],
            "foreign-relation": null,
            "foreign-constraint": null,
            "on-store": null,
            "on-update": null
        },
        {
            "name": "description",
            "labels": {
                "en": "Description",
                "ar": "Description"
            },
            "html-type": "textarea",
            "css-class": "",
            "options": {},
            "html-value": null,
            "validation": "string|min:1|max:1000",
            "is-on-index": false,
            "is-on-show": true,
            "is-on-form": true,
            "data-type": "string",
            "data-type-params": [
                1000
            ],
            "data-value": null,
            "is-index": false,
            "is-unique": false,
            "is-primary": false,
            "comment": null,
            "is-nullable": true,
            "is-header": false,
            "is-unsigned": false,
            "is-auto-increment": false,
            "is-inline-options": false,
            "is-date": false,
            "date-format": "",
            "cast-as": "",
            "placeholder": {},
            "delimiter": "; ",
            "range": [],
            "foreign-relation": null,
            "foreign-constraint": null,
            "on-store": null,
            "on-update": null
        },
        {
            "name": "is_verified",
            "labels": {
                "en": "Is Verified",
                "ar": "Is Verified"
            },
            "html-type": "checkbox",
            "css-class": "",
            "options": {
                "en": {
                    "0": "No",
                    "1": "Yes"
                },
                "ar": {
                    "0": "No",
                    "1": "Yes"
                }
            },
            "html-value": null,
            "validation": "boolean",
            "is-on-index": true,
            "is-on-show": true,
            "is-on-form": true,
            "data-type": "bool",
            "data-type-params": [],
            "data-value": null,
            "is-index": false,
            "is-unique": false,
            "is-primary": false,
            "comment": null,
            "is-nullable": true,
            "is-header": false,
            "is-unsigned": false,
            "is-auto-increment": false,
            "is-inline-options": false,
            "is-date": false,
            "date-format": "",
            "cast-as": "",
            "placeholder": {},
            "delimiter": "; ",
            "range": [],
            "foreign-relation": null,
            "foreign-constraint": null,
            "on-store": null,
            "on-update": null
        },
        {
            "name": "is_active",
            "labels": {
                "en": "Is Active",
                "ar": "Is Active"
            },
            "html-type": "checkbox",
            "css-class": "",
            "options": {
                "en": {
                    "0": "No",
                    "1": "Yes"
                },
                "ar": {
                    "0": "No",
                    "1": "Yes"
                }
            },
            "html-value": null,
            "validation": "boolean",
            "is-on-index": true,
            "is-on-show": true,
            "is-on-form": true,
            "data-type": "bool",
            "data-type-params": [],
            "data-value": null,
            "is-index": false,
            "is-unique": false,
            "is-primary": false,
            "comment": null,
            "is-nullable": true,
            "is-header": false,
            "is-unsigned": false,
            "is-auto-increment": false,
            "is-inline-options": false,
            "is-date": false,
            "date-format": "",
            "cast-as": "",
            "placeholder": {},
            "delimiter": "; ",
            "range": [],
            "foreign-relation": null,
            "foreign-constraint": null,
            "on-store": null,
            "on-update": null
        }
    ],
    "relations": [],
    "indexes": [],
    "auto-manage-created-and-updated-at": true,
    "table-name": null,
    "protection": {
        "is-model-protected": false,
        "is-controller-protected": false,
        "is-form-request-protected": false,
        "is-languages-protected": false,
        "is-form-view-protected": false,
        "is-index-view-protected": false,
        "is-create-view-protected": false,
        "is-edit-view-protected": false,
        "is-show-view-protected": false
    }
}

**Comment by CrestApps** [comment]
Change your command to the following
```
php artisan resource-file:create Category --force
--fields=id,name,description,is_verified,is_active
--translation-for=en,ar
--relations="name:items;type:hasMany;field:title;params:App\Models\Item|item_id|id,"
```

I changed the `=` after `params` to `:`.

**Comment by heingithub** [comment]
Thank you for spotting that one, silly mistake.

**Comment by CrestApps** [comment]
No worries! 
Don't forget to Start the package :)
