### ISSUE TITLE
Error generated View from json sources

### ISSUE THREAD

**Issue by diorz38** [CrestApps/laravel-code-generator#45]
### Environment:
- Laravel-Code-Generator Version: 2.2
- Laravel Version: 5.4.21

### Description: when i generate resource, controller and view from database, i get error that someting in code is missing:
error said:
Error 1 (when access index page):
ErrorException in c75b045f0ae7f8ff8938d98333ec52acf2ea467c.php line 107: Parse error: syntax error, unexpected 'Project' (T_STRING), expecting ']' (View: C:\laragon\www\siloka2018\resources\views\projects\index.blade.php)

I can manage this error, by add an apostrophe:
Origin:
{!! Form::button('<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>', 
                                            [   
                                                'type'    => 'submit',
                                                'class'   => 'btn btn-danger',
                                                'title'   => Delete Project,
                                                'onclick' => 'return confirm("' . Delete Project? . '")'
                                            ])
                                        !!}

Fixed:
{!! Form::button('<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>', 
                                            [   
                                                'type'    => 'submit',
                                                'class'   => 'btn btn-danger',
                                                'title'   => 'Delete Project',
                                                'onclick' => 'return confirm("' . 'Delete Project?' . '")'
                                            ])
                                        !!}
 
Error 2 (when call create.blade.php):
ErrorException in a3a83ea0a91aee7819490944b01309df743477bc.php line 6: Parse error: syntax error, unexpected '<' (View: C:\laragon\www\siloka2018\resources\views\projects\form.blade.php) (View: C:\laragon\www\siloka2018\resources\views\projects\form.blade.php)

### Steps/Commands To Reproduce: 

1. create resource's file from existing database
2. create resources from above source, with this command: 
    php artisan create:resources Project --with-form-request --models-per-page=15 --with-migration

    i use default-collective for the template

### Content Of The Resource-File:
[projects.json.zip](https://github.com/CrestApps/laravel-code-generator/files/1651525/projects.json.zip)

**Comment by CrestApps** [comment]
I am unable to reproduce the issue your having. Your templates may not be up-to-date, so try to republish the templates to ensure your using the latest.
```
php artisan vendor:publish --provider="CrestApps\CodeGenerator\CodeGeneratorServiceProvider" --force
```
After publishing is completed, try to regenerate the resources again with the `--force` option to override your existing files.

Also, the `projects.json` you attached is missing options for the `select` html inputs. You should edit it and add at least one option in each element.

**Comment by CrestApps** [comment]
Did the above instruction solve your issue?
