### ISSUE TITLE
Title attribute is not convenient on mobile

### ISSUE THREAD

**Issue by eduardoarandah** [CrestApps/laravel-code-generator#46]
### Environment:
Iphone 5s + safari

### Description:

When title attribute is set on link buttons, you need to click twice on iphone to trigger the click, which is confusing. 

I suggest removing it. 
I guess the title attr is good for SEO reasons in public pages, but this is not the case. 

example: 
`<a href="{{ route('[% create_route_name %]') }}" class="btn btn-success" title="[% create_model %]">`

**Comment by CrestApps** [comment]
What view are you referring to?

**Comment by eduardoarandah** [comment]
Well, I searched with sublimetext 

`title=".+"`

and gave me these:

templates\default\create.blade.stub
templates\default\edit.blade.stub
templates\default\index.blade.stub
templates\default\show.blade.stub
templates\default-collective\create.blade.stub
templates\default-collective\edit.blade.stub
templates\default-collective\index.blade.stub
templates\default-collective\show.blade.stub

I don't think title attribute has any significant value in todays web, only a tooltip, and there's better tooltips if that functionality is needed.

**Comment by CrestApps** [comment]
The title may improve SEO for the app. I am unable to reproduce the issue your mentioning. I pulled up the demo on iPhone with safari and everything seems to be working as expected you can evaluate the demo on an iPhone https://www.crestapps.com/laravel-code-generator/demos/v2-2

**Comment by eduardoarandah** [comment]
you're right. I can't reproduce error in demo. 
I'll check on what conditions it gave me error.
