### ISSUE TITLE
How can I modify index view using DataTables?

### ISSUE THREAD

**Issue by gettedgui** [CrestApps/laravel-code-generator#51]
It is possible to modify index views using DataTables?
How can I do that?

I suggest to incorporate DataTables to index views

Thanks

### Environment:
- Laravel-Code-Generator Version: 2.2
- Laravel Version: 5.5

### Description:
Create the index views with --with-datatables parameter
This create an index view using DataTables

### Steps/Commands To Reproduce:
php artisan create:resource Model --with-datatables
php artisan create:views Model --with-datatables
php artisan create:index-view Model --with-datatables

**Comment by CrestApps** [comment]
There is no plan on adding DateTable option in the commands as that it the wrong approach. However, you should be able to accomplish what your looking to do using a [custom template](https://www.crestapps.com/laravel-code-generator/docs/2.2#how-to-create-custom-template).

So you create a template called `DataTables`  and once your done, you can let the code generator use your custom template like so.
```
php artisan create:resource Model -- template-name=DataTables
```
Also, once your done I recommend that you publish this template on GitHub to help others whom looking to use DataTables.

**Comment by gettedgui** [comment]
Thanks

Atentamente,

Gustavo Enrique Ettedgui Ponce

2018-03-14 14:22 GMT-04:00 CrestApps <notifications@github.com>:
