### ISSUE TITLE
Cant Create Resource from Existing table

### ISSUE THREAD

**Issue by diorz38** [CrestApps/laravel-code-generator#53]
### Environment:
- Laravel-Code-Generator Version: 2.3.#
- Laravel Version: 5.5.39

### Description:
When i run command: 

php artisan resource-file:from-database Mitra
or
 php artisan create:scaffold Mitra --table-exists

I got error:
In MysqlParser.php line 18:

  Cannot make non static method CrestApps\CodeGenerator\DatabaseParsers\ParserBase::getModelNamespace() static in cla
  ss CrestApps\CodeGenerator\Traits\ModelTrait

my Existing table name is mitras

### Content Of The Resource-File:

[mitras.zip](https://github.com/CrestApps/laravel-code-generator/files/1818750/mitras.zip)

**Comment by CrestApps** [comment]
Fixed.
