### ISSUE TITLE
Custom Model Template - Configuration Options

### ISSUE THREAD

**Issue by LarryTX** [CrestApps/laravel-code-generator#55]
### Environment:
- Laravel-Code-Generator Version:2.2.7
- Laravel Version: 5.6.12

### Description:
Attempting to create custom template as suggested in procedures. 

### Steps/Commands To Reproduce:
Specifically trying to create a modified model.stub to add `use Cviebrock\EloquentSluggable\Sluggable;` and `use Sluggable; `along the lines of what is currently done with soft deletes. Could not find any procedures for adding such options. Tried simply entering the information in the model.stub, but the model output had blank space where I had entered the information.

Ultimately, there would probably be many other modifications that would be desirable, but without instructions on how to do it, it's simply a matter of wandering blindly in the dark.
### Content Of The Resource-File:
See attached text file.
[entities.txt](https://github.com/CrestApps/laravel-code-generator/files/1827582/entities.txt)

You've got a fantastic generator, far better than most of what I've seen in the Laravel ecosystem that just produce stubs without any content, the type of thing that you can almost type in faster than using the extension. I hope you'll keep up all the great work! It would be really helpful to have some clearer instructions on making custom templates, but I want to say that the rest of your instructions are, just like the generator itself, far superior to most of what I've seen in the Laravel arena. Having worked with Yii2 for many, many years, I'm glad to see that Laravel is finally catching up!

**Comment by CrestApps** [comment]
You may want to review the basic instructions on how to create a [template in the config file](https://github.com/CrestApps/laravel-code-generator/blob/master/config/codegenerator.php#L5-L45) and the basic instruction on the [documentation page.](https://crestapps.com/laravel-code-generator/docs/2.2#how-to-create-custom-template)

Lets say you want to create a new template called `Sluggable`. Then, you'll need to make a copy of the `resources/laravel-code-generator/templates/default` folder and call the new folder `Sluggable`.

Now go edit the `resources/laravel-code-generator/templates/default/model.stub` file to make it fit your needs.

If all you're trying to do is simple add the `use Cviebrock\EloquentSluggable\Sluggable;`

Then find the `[% use_soft_delete_trait %]` line and add `use Cviebrock\EloquentSluggable\Sluggable;` just before it.

I hope that helps.

**Comment by LarryTX** [comment]
As I mentioned in my issue, I did exactly that, and it most definitely did not work. I copied model.stub to a memehope directory and modified it to look like this:

[cid:image001.png@01D3BFDC.2E069510]

When I produced the model, it looked like this:

[cid:image002.png@01D3BFDC.CB1D4600]

Note the blank lines where the sluggable information was in model.stub. This is precisely what I said was happening in my original issue when I stated, “Tried simply entering the information in the model.stub, but the model output had blank space where I had entered the information.”

In addition, the soft deletes material does not appear unless you add –with-soft-delete to the artisan command. I’m totally unable to find that in your instructions. I must be blind.

As to reviewing your basic instructions, in my issue I stated, “ It would be really helpful to have some clearer instructions on making custom templates, but I want to say that the rest of your instructions are, just like the generator itself, far superior to most of what I've seen in the Laravel arena.” How do you think I could have said that if I hadn’t read your instructions in great detail. Perhaps, if you read the issue, you might have been able to respond to it.

Larry E. Lutz

**Comment by CrestApps** [comment]
I am trying to understand the problem here. But unable to fully follow you.

It sounds like you correctly created a template named `memehope`. Did you provide the template name to the generator? (i.e `php artisan create:model YourModelName --template-name=memehope`) If you did that and you still not seeing your template being used, please upgrade to [v2.2.8](https://github.com/CrestApps/laravel-code-generator/releases/tag/v2.2.8) which was just released, you could be impacted buy a bug that was impacting custom templates.

Let me know if that works for you.

**Comment by LarryTX** [comment]
No.


  1.  I created a directory called /resources/codegenerator-templates/memehope.
  2.  I copied model.stub from the default directory to the memehope directory.
  3.  I modified model.stub to add the sluggable directives.
  4.  I produced the model using the artisan directive: php artisan create:model Entity --resource-file=entities.json --model-directory="Modules\Entity\Entities" --with-soft-delete --template-name=memehope

This directly parallels your instructions which state: To create a custom template, simply duplicate /resources/codegenerator-templates/default folder, then name it anything you like. For example, bluesky.

Now, make all the custom changes in the bluesky folder.

The only difference is that I called my new folder memehope instead of bluesky.

Larry E. Lutz

**Comment by CrestApps** [comment]
I just did the same thing you did using v2.2.8, and everything worked fine for me.  Here is how my model looks like
![screenshot_8](https://user-images.githubusercontent.com/24724371/37637391-b94d94f8-2bc4-11e8-8ee1-0564eb024012.png)
[Entity.txt](https://github.com/CrestApps/laravel-code-generator/files/1828026/Entity.txt)


I recommend that you upgrade to v2.2.8 and try again.

**Comment by LarryTX** [comment]
It does not appear that 2.2.8 is available for upgrade. See the results.
![generator 2 2 8](https://user-images.githubusercontent.com/20743/37637632-c3440070-2bd6-11e8-926c-c5e0c33cfc87.png)

Also, 2.2.8 is not listed on packagist.org.
![generator packagist](https://user-images.githubusercontent.com/20743/37637643-d43cb354-2bd6-11e8-8c43-f415fb5d4882.png)

By the way, if a way is found to modify the template that works, do I include the change by specifying --with-sluggable comparable to --with-soft-delete? At his point, it appears, if it ever works, that the sluggable information would be in ever model created with that template. Having to create a different template for every possible modification of the template would be mind-boggling.

**Comment by CrestApps** [comment]
That was my fault. Please try clearing out your composer cache and try again

```
composer clear-cache
composer update
```

**Comment by LarryTX** [comment]
That worked. Thanks.

Larry E. Lutz

**Comment by CrestApps** [comment]
Glad it did.
