### ISSUE TITLE
Can you think about add depend tables

### ISSUE THREAD

**Issue by gettedgui** [CrestApps/laravel-code-generator#56]
I need to know how I can generete a code for tables related. For example: An invoice with relate clients table (using several fields like name, address, telephone) and relate with details table showing a list of details wich is related with products table with several fields too. Is there a configuration that allow do that?

### Environment:
- Laravel-Code-Generator Version: #.#.#
- Laravel Version: #.#.#

**Comment by CrestApps** [comment]
What are you trying to generate here?
I would think you would want to create a CRUD for the Invoice and another for Clients.

If that is the case, you should be able to create what your looking to do using the following commands at a high level

php artisan resource-file:create Client --fields=id,name,telephone,address,city,state,zip_code,country
php artisan resource-file:create Invoice --fields=id,title,client_id
php artisan resource-filecreate InvoiceLineItem --fields=id,invoice_id,title,amount

php artisan create:resources Client
php artisan create:resource Invoice
php artisan create:resource InvoiceLineItem 

I hope this puts you on the right track

**Comment by gettedgui** [comment]
Ok. I did that. But my problem is when I want to create a view-create
Invoice where:

If I select any client (this is easy), I need to show all the information
of that client (I don't know how make a resource file .json to show the
others fields)
Then I need to add the invoice information (easy too)
Finally, I need to show and index only with InvoiceLineItem belongs to the
same invoice where I must add, edit or delete each element of the line

Sorry if my English is to hard to understand and really thank you for your
time

Atentamente,

Gustavo Enrique Ettedgui Ponce

2018-03-20 15:47 GMT-04:00 CrestApps <notifications@github.com>:

**Comment by CrestApps** [comment]
The code generator will simple create the CRUD code for you. From there, you should lock the resource to protect yourself from you, then extend the code to accommodate your needs. You'll need to add JS code to show the client info when the client is selected on the menu. Also, you'll need to include the lineItems index view in the  Invoice show view.
