### ISSUE TITLE
How to handle different base namespace?

### ISSUE THREAD

**Issue by ericniaina** [CrestApps/laravel-code-generator#59]
### Environment:
- Laravel-Code-Generator Version: 2.2.#
- Laravel Version: 5.6.#

### Description:
I got a
ReflectionException  : Class App\Http\Kernel does not exist
when the command try to create a controller.
It's because i don't use the namespace App.

### Steps/Commands To Reproduce:
Install laravel
change app name with
```
php artisan app:name 
```
install laravel-code-benerator
try the basic generation example

**Comment by CrestApps** [comment]
Yes that was a bug. Please run `composer update` to upgrade to v2.2.9 which fixes this issue.
