### ISSUE TITLE
Small typo in documentation at https://www.crestapps.com/ website

### ISSUE THREAD

**Issue by vanameister** [CrestApps/laravel-code-generator#62]
### Environment:
- Laravel-Code-Generator Version: #.#.#
- Laravel Version: #.#.#

### Description:
I had some difficulty to create relations for resource file, based on the example given in the documentation. It took me couple of hours reading and debugging the code to pin it down.. There is equal sign in the documentation, but colon should be used:

--relations="name:comments;type:hasMany;field:title;params=App\Models\Comment|post_id|id,"
should be
--relations="name:comments;type:hasMany;field:title;params:App\Models\Comment|post_id|id,"

And thanks for really great and useful code!

**Comment by CrestApps** [comment]
The typo in the docs was fixed.

Thank you.
