### ISSUE TITLE
Wish: set global namespace and layout

### ISSUE THREAD

**Issue by eduardoarandah** [CrestApps/laravel-code-generator#63]
this is not an issue, just a feedback

when programming a site with frontend/backend I wish I could set these options in the config:

views_path
requests_path
routes_prefix
layout_name

why?

When doing the backend, for any model, code goes like this.

- controllers/admin/dog
- requests/admin/dog
- views/admin/dog/index
- views/admin/dog/create
- views/admin/dog/edit
...

and routes are 

admin.dog.index
admin.dog.create
admin.dog.edit
...

and all use a layout like "layouts.backend"

Then, when doing frontend, all things the same, but with "frontend"

**right now all this is possible** by adding parameters to command line, which is great!

but it would be awesome (for lazy people like me) to just set these in the config and run 

`php artisan create:resources dog`

and (a week later) change the config to "frontend" and run the same command for all the frontend code

what do you think?

**Comment by CrestApps** [comment]
You should be able to accomplish what you want by using the config file. When you’re developing the frontend, modify the config file by post fixing all the *_paths with the word “frontend”. Then change it when you develop “backend” accordingly.
