### ISSUE TITLE
Extending config

### ISSUE THREAD

**Issue by nenads** [CrestApps/laravel-code-generator#66]
### Environment:
- Laravel-Code-Generator Version: "^2.2",
- Laravel Version: "5.6.*",

### Description:
When adding new match it config it is ignored: example: 
 'match' => '*_encrypted',. 

but when modifiyng existant rule like 'match' => ['id'] all works

### Steps/Commands To Reproduce:
config\codegenerator_custom.php
`'common_definitions' =>
  [
     [
         'match' => '*_encrypted',
         'set' => [
             "on-update" => 'Illuminate\Support\Facades\Auth::Id();',
         ],
     ],
     [
         'match' => ['id'],
         'set' => [
             'title' => 'Updater',
             'data-type' => 'integer',
             'foreign-relation' => [
                 'name' => 'updater',
                 'type' => 'belongsTo',
                 'params' => [
                     'App\\User',
                     'updated_by',
                 ],
                 'field' => 'name',
             ],
             'on-update' => 'Illuminate\Support\Facades\Auth::Id();',
         ],
     ],
  ]`

### Content Of The Resource-File:

`{
    "fields": [
        {
            "name": "id",
            "labels": "Id",
            "html-type": "select",
            "css-class": "",
            "options": {},
            "html-value": null,
            "validation": "",
            "is-on-index": false,
            "is-on-show": false,
            "is-on-form": false,
            "data-type": "int",
            "data-type-params": [],
            "data-value": null,
            "is-index": false,
            "is-unique": false,
            "is-primary": true,
            "comment": null,
            "is-nullable": true,
            "is-header": false,
            "is-unsigned": true,
            "is-auto-increment": true,
            "is-inline-options": false,
            "is-date": false,
            "date-format": "",
            "cast-as": "",
            "placeholder": "Enter id here...",
            "delimiter": "; ",
            "range": [],
            "foreign-relation": {
                "name": "updater",
                "type": "belongsTo",
                "params": [
                    "App\\User",
                    "updated_by"
                ],
                "field": "name"
            },
            "foreign-constraint": null,
            "on-store": null,
            "on-update": "Illuminate\\Support\\Facades\\Auth::Id();"
        },
        {
            "name": "test",
            "labels": "Test",
            "html-type": "text",
            "css-class": "",
            "options": {},
            "html-value": null,
            "validation": "string|min:1",
            "is-on-index": true,
            "is-on-show": true,
            "is-on-form": true,
            "data-type": "string",
            "data-type-params": [],
            "data-value": null,
            "is-index": false,
            "is-unique": false,
            "is-primary": false,
            "comment": null,
            "is-nullable": true,
            "is-header": false,
            "is-unsigned": false,
            "is-auto-increment": false,
            "is-inline-options": false,
            "is-date": false,
            "date-format": "",
            "cast-as": "",
            "placeholder": "Enter test here...",
            "delimiter": "; ",
            "range": [],
            "foreign-relation": null,
            "foreign-constraint": null,
            "on-store": null,
            "on-update": null
        }
    ],
    "relations": [],
    "indexes": [],
    "auto-manage-created-and-updated-at": true,
    "table-name": null,
    "protection": {
        "is-model-protected": false,
        "is-controller-protected": false,
        "is-form-request-protected": false,
        "is-languages-protected": false,
        "is-form-view-protected": false,
        "is-index-view-protected": false,
        "is-create-view-protected": false,
        "is-edit-view-protected": false,
        "is-show-view-protected": false
    }
}`

**Comment by CrestApps** [comment]
Indeed that was a bug. I just released new version (i.e. v2.2.11) with the fix. Please update the package and test it out.
