### ISSUE TITLE
Why can't models extend a supplied base, like controllers can?

### ISSUE THREAD

**Issue by CyberiaResurrection** [CrestApps/laravel-code-generator#67]
### Environment:
Laravel-Code-Generator Version: 2.2.7
Laravel Version: 5.5.40

### Description:
A consistency thing I've tripped over.  Controller creation can take a specific base controller (eg BaseController), but at the moment, model creation can't take an analogous base model (eg BaseModel).

### Steps/Commands To Reproduce:
N/A

### Content Of The Resource-File:
N/A

**Comment by CrestApps** [comment]
We try to follow Laravel code. By default Laravel does not use base class for model where the controller does. Since BaseModel isn’t required or exists we simply don’t have one. I may add an option in future releases where you can pass an that will allow you to create the controller with-base-model

**Comment by CrestApps** [comment]
I added this as an option to breach v2.3 which is where the new version currently reside.
