### ISSUE TITLE
Datetime input -> wrong values -> config and strtotime format issue

### ISSUE THREAD

**Issue by nenads** [CrestApps/laravel-code-generator#68]
### Environment:
- Laravel-Code-Generator Version: 2.2.# (Maybe this applay to 2.3 version too)
- Laravel Version: 5.6.#

### Description:
When using default config with datetime fileds there are unexpected result.
Code gen muttators when creating 

'datetime_out_format' => 'j/n/Y g:i A',

example generated mutator

`$this->attributes['starts_at'] = !empty($value) ? date($this->getDateFormat(), strtotime($value)) : null;`

### Steps/Commands To Reproduce:
```
<?php

//Laravel
/**
 * Get the format for database stored dates.
  public function getDateFormat()
  {
       return 'Y-m-d H:i:s';
  }
  */

//codegenerator format
//'datetime_out_format' => 'j/n/Y g:i A';

$laravelGramagetDateFormat= "Y-m-d H:i:s";
$dates=["1/1/2018 12:00 AM","12/12/2018 12:00 AM","28/1/2018 12:00 AM","31/1/2018 12:00 AM"];

$format = "%s   >   %s  >   %s\n";
echo sprintf($format, 'input','timestamp','converted');

foreach($dates as  $date){
    echo sprintf($format, $date, strtotime($date), date($laravelGramagetDateFormat, strtotime($date)));
}
```
result

```input   >   timestamp  >   converted
1/1/2018 12:00 AM   >   1514793600  >   2018-01-01 00:00:00
12/12/2018 12:00 AM   >   1544601600  >   2018-12-12 00:00:00
28/1/2018 12:00 AM   >     >   1969-12-31 16:00:00
31/1/2018 12:00 AM   >     >   1969-12-31 16:00:00
```

Need to include this 

From Note:

Dates in the m/d/y or d-m-y formats are disambiguated by looking at the separator between the various components: if the separator is a slash (/), then the American m/d/y is assumed; whereas if the separator is a dash (-) or a dot (.), then the European d-m-y format is assumed. If, however, the year is given in a two digit format and the separator is a dash (-), the date string is parsed as y-m-d.

To avoid potential ambiguity, it's best to use ISO 8601 (YYYY-MM-DD) dates or DateTime::createFromFormat() when possible.

**Comment by CrestApps** [comment]
Hi,
Thank you for your feedback here. I update the templates, please try it out and let me know if that works for you 

https://github.com/CrestApps/laravel-code-generator/commit/ab8dd2ea79c19a3ca4a9b82d50e48753bad6c6ed
