### ISSUE TITLE
can't get files

### ISSUE THREAD

**Issue by almiali** [CrestApps/laravel-code-generator#71]
Hi

I can't get any file that I uploaded using the tools

I trying to use php artisan storage:link but that not solve the problem

thank you

**Comment by CrestApps** [comment]
Can you please explain? What have you done? What are the expected behavior and what are the current results? Also please share the generated code

**Comment by almiali** [comment]
I use that example

php artisan resource-file:create Biography --fields=id,name,age,biography,sport,gender,colors,is_retired,photo,range,month
php artisan create:resources Biography --with-form-request --models-per-page=15 --with-migration


but I tried to open the photo that I upload on Photo filed, I can't access that photo, I worked on localhost and also tried to write php artisan storage:link , nothing is changed 

 
(tring to open that photo)
![image](https://user-images.githubusercontent.com/40799745/43682668-631d968c-9884-11e8-8f7e-b9e7be186271.png)

**Comment by almiali** [comment]
I found the problem

after run php artisan storage:link 

you should change upload path into      'files_upload_path' => 'public/uploads',

thank you

**Comment by almiali** [comment]
Hi

Can I change the path that saved on the database?

thank you

**Comment by CrestApps** [comment]
That is an issue with the package. I need to fix up both `controller-upload-method.stub` and `controller-upload-method-53.stub`

Additionally, so far the package only allow you to show the base-name of the file not rendering the image. But I'll be sure to add an option to allow you to change how files are visible too.

**Comment by CrestApps** [comment]
You should not change the upload path in the config. Please upgrade the code generator to the latest version and the publish your resources 

```
php artisan vendor:publish --provider="CrestApps\CodeGenerator\CodeGeneratorServiceProvider" --tag=default
```

**Comment by almiali** [comment]
hi
I checked the files there is no change on file controller-upload-method.stub

thank you

**Comment by CrestApps** [comment]
controller-upload-method.stub is for older versions of Laravel. Since your on 5.3+ then the stub that would impact you would be[ controller-upload-method-5.3.stub](
https://github.com/CrestApps/laravel-code-generator/blob/master/templates/default/controller-upload-method-5.3.stub)
