### ISSUE TITLE
Translation Issue in templates

### ISSUE THREAD

**Issue by nenads** [CrestApps/laravel-code-generator#72]
### Environment:
- Laravel-Code-Generator Version: 2.3.#
- Laravel Version: 5.6.#

### Description:

When using translation it seems that at one place template is targeting main lan file.
### Steps/Commands To Reproduce:

php artisan create:scaffold Device --fields=id,name --translation-for=en,sr

### Content Of The Resource-File:

![image](https://user-images.githubusercontent.com/1824176/43687851-8162b9d4-98dd-11e8-86a9-fea0a564c26c.png)

**Comment by nenads** [comment]
Do you have discord or slack ?

**Comment by CrestApps** [comment]
I do not use discord or slack. Can you please share the commands you used to generate the issue?

**Comment by nenads** [comment]
php artisan create:scaffold Device --fields=id,name --controller-directory=Admin --views-directory=Admin --model-directory=Admin --form-request-directory=Admin  --with-form-request --with-auth --with-migration --translation-for=en,sr

**Comment by CrestApps** [comment]
This issue should be fixed now. Please pull the latest code and let me know if you run into any other issues.
