### ISSUE TITLE
change file path to image preview

### ISSUE THREAD

**Issue by almiali** [CrestApps/laravel-code-generator#74]
Hi

how I can change the link of the image in the index to preview image 

I searched in the template and I don't find anything

![image](https://user-images.githubusercontent.com/40799745/43826888-219807e0-9b01-11e8-8f54-df58af204134.png)

thank you

**Comment by CrestApps** [comment]
First of all you should upgrade to the latest version and there was a bug in the upload file handling.
We currently don't have an option to allow you to render a file into an `<img src="">` tag. For now, you'll have to manually edit your generated views and wrap the generated link with an `<img ...>` tag

Something like this
```
 <img src="{{ asset('storage/' . $modelName->picture) }}" alt="" /> 
```

At some point we'll add this as an option to allow you to easily control it.
