### ISSUE TITLE
Get error when publishing the package

### ISSUE THREAD

**Issue by diorz38** [CrestApps/laravel-code-generator#75]
### Environment:
- Laravel-Code-Generator Version: 2.3.x-dev
- Laravel Version: 5.5.42

### Description:
Get error when publishing package:

```diff
- Can't locate path: <d:\laravel\vendor\crestapps\laravel-code-generator\src/../config/codegenerator.php>
+ Copied Directory [\vendor\crestapps\laravel-code-generator\templates\default] To [\resources\laravel-code-generator\templates\default]
+ Copied Directory [\vendor\crestapps\laravel-code-generator\templates\default-collective] To [\resources\laravel-code-generator\templates\default-collective]

```

### Steps/Commands To Reproduce:
from fresh Laravel Instalation, and add `"crestapps/laravel-code-generator": "2.3.x-dev",` to composer.json, after run `composer update`
run `php artisan vendor:publish`

**Comment by CrestApps** [comment]
I’ll check to see why you are running into that error.

Note that in 2.3-dev you don’t need to publish the resource like we do in 2.2

**Comment by CrestApps** [comment]
This issue is fixed now. But like mentioned above, unless you have a good reason to publish, you should not need to publish the resource.
