### ISSUE TITLE
Namespace models and from-database issue

### ISSUE THREAD

**Issue by nenads** [CrestApps/laravel-code-generator#77]
### Environment:
- Laravel-Code-Generator Version: 2.3.#
- Laravel Version: 5.6.#

### Description:

When having models with more depth then just App\Models you cant create resource from existing database.

### Steps/Commands To Reproduce:

php artisan resource-file:from-database "\\App\\Models\\Test\\Some" --table-name=tests --translation-for=en,sr

### Content Of The Resource-File:

![image](https://user-images.githubusercontent.com/1824176/44048007-7602169e-9f30-11e8-817b-c20caadf3845.png)

**Comment by CrestApps** [comment]
try changing your command to this instead

php artisan resource-file:from-database Some --model-directory="App\Models\Test" --table-name=tests --translation-for=en,sr

**Comment by nenads** [comment]
The "--model-directory" option does not exist.

when i change in
CrestApps\CodeGenerator\Traits\ModelTrait

public static function getModelNamespace($modelName, $modelDirectory = null) 

It passes since this function expect two arguments.

**Comment by CrestApps** [comment]
Ouch! I'll dig into the issue when time permits. I am glad your that you're testing v 2.3

**Comment by CrestApps** [comment]
sorry, I just thought about something. the `resource-file` would only create the resource file, it has nothing to do with how the model is generated. Are you trying to create the resource-file in a sub-folder or you're just trying to create the model in a subfolder?

if you're just trying to create the model in a subfolder, then do the following to create the resource-file from the database
```
php artisan resource-file:from-database Some --table-name=tests --translation-for=en,sr
```

then you can create the model using the following command
```
php artisan create:model Some --model-directory="App\Models\Test" --table-name=tests --translation-for=en,sr
```

or you can create all the resources along with the resource file like so
```
php artisan create:scaffold Some --model-directory="App\Models\Test" --table-name=tests --table-exists --translation-for=en,sr
```
Let me know if that is what you're looking for or something else

**Comment by CrestApps** [comment]
I am trying to understand if you're trying to create a resource file or a model. Please check my [previous comments ](https://github.com/CrestApps/laravel-code-generator/issues/77#issuecomment-412619915)

**Comment by nenads** [comment]
My conclusion is that resource-file:from-database is using old calls

![image](https://user-images.githubusercontent.com/1824176/44089925-c5c87e78-9fc8-11e8-8340-ebf0272d79fa.png)

**Comment by CrestApps** [comment]
I fixed the bug that you ran into. Pull the latest should fix it.

I am having hard time following your method/workflow. Why do you need the code-generator to create a base class for the models? If for some reason you need to extend a different class than the `Illuminate\Database\Eloquent\Model` class, you should be able to pass `--model-extends` property with the full-name of the base model. for example `--model-extends="App\Models\Base\Post"

If you're admin look the same, you should not need to edit the code/views manually each time. You can be wasting a lot of time. Instead, you should create a new template for your admin work and use the admin_template when creating code. Your goal should be creating the code with almost no need to change the generated code manually. The controller/scaffold command gives you the `--with-auth` option which adds the proper code if your using [Laravel-Passport ](https://laravel.com/docs/5.6/passport) for your authentication. If you're using other packages than laravel-passport, then you should be able to add the needed code in the admin_template directly so the generated code will be ready and no need to ever edit it. The idea here is to prevent you from having the need to edit files manually which will save you time and will allow you to regenerate the resources if you ever need to change the look/feel of your site without having the need to manually do the work.

If I missed something from your comments above, then please share some code example with me so I can help you better. Show me the commands you used, the table structure of your database, the generated code and how it looks after your edit. this will help me understand the changes.

**Comment by CrestApps** [comment]
Note if you have a chat room that you like me to join, please email me the instructions of the email found in the `composer.json` file found in the project.
