### ISSUE TITLE
QUESTION: Flexibility in templates' stubs contents (available {{labels}} to parse in each stub) [enhancement] [edited]

### ISSUE THREAD

**Issue by essemme** [CrestApps/laravel-code-generator#8]
I made a "custom" template directory (as suggested in the docs). 
Everything works beautifully, except for one peculiar thing.
I'm trying to add some simple features (gettext string translations, url keeping querystrings, and some other).

The problem is both the parsing of the stub and the blade template engine use double curly braces (probably not so relevant) - and, beyond that, parsing of "nested" snippets messes things up, causing errors due nested php/php echo tags.

examples: 

`{!! isset({{modelHeader}}) ? {{modelHeader}} : _i("{{modelNamePluralCap}}") !!}`
gives
`{{ isset({{modelHeader}}) ? {{modelHeader}} : _i("MyModels") }}`

`{!! Request::fullUrlWithQuery ( [ 'o' => '{{fieldName}}' ] ) !!}">{{ _i("{{fieldTitle}}") }}`
becomes 
`{!! Request::fullUrlWithQuery ( [ 'o' => '{{fieldName}}' ] ) !!}">{{ _i("Code") }}`
(the one written as nested single argument is parsed, the other one not)

I tried different combinations (using {!!, @{{, @php) but I often get the stub variable not parsed in the resulting view (${{modelName}} instead of $model) - resulting in an earlier ?php> closing tag due to wrong matching of the nested brackets once the blade view is parsed.    
  
Maybe I'm missing something obvious (and I didn't take the time yet to dig into the parsing code).
Any suggestions on the best way to handle this?

**Comment by essemme** [comment]
I took a quick look at the relevant code - being most (all?) of the substitution a str_replace() of the exact label, the nesting shouldn't be a problem - maybe there is something interfering.
`$stub = str_replace('{{fieldName}}', $fieldName, $stub); `
should work anyway.

I'll check if it's something outside of the scope of the package (related to my specific case, as I'm adapting the generators templates with adminlte layout and mixing a couple of other plugins for multi language contents and gettext interface translations).

It would be great if someone else could confirm it's a general issue (or just my case)

**Comment by essemme** [comment]
Ok, just took a quick but deeper look with xdebug.
So it seems, the only problem is, I copied some labels to other stub files that that are not parsed for those labels.
Example: 
`{!! Request::fullUrlWithQuery ( [ 'o' => '{{fieldName}}' ] ) !!}">{{ _i("{{fieldTitle}}")   `
replaced the default "{{fieldTitle}}" in index.header.cell.blade.stub
(I was adding sorting links to the columns' headers)
The HtmlGeneratorBase::getIndexHeaderCells() method (obviously) only parses {{fieldTitle}}.
$this->replaceFieldTitle([..])

Obviously, parsing different stubs only looking for the expected labels in very effective and efficient, while parsing every single stub file using every replaceSomething and related data method would be less efficient and more complex; but it imposes some limitations on the editing possibilities of the custom template - the kind of content that can be used in a specific stub file is tightly coupled with the parser classes code.

I suppose the template customization feature was primarily meant for adapting the presentation markup, which is great. 
Adding some flexibility in the view logic would also be great (it seems reasonable to edit template files to add view related features, like the aforementioned sorting links; or maybe something more complex like datatables and other js interface elements).
It's easy to edit the resulting files, it would be great to just be able to edit the generators templates using all available elements in every view stub.

What do you think about it?

(I'm not going to make a pull request, as this is a design choice, I'll just leave this here as a question)

**Comment by essemme** [comment]
Started messing with the code - here is an example (some content i needed in my custom views/partials stubs)
[commit in forked experimental branch](https://github.com/essemme/laravel-code-generator/commit/ac8f66674fba0165b753ecb9de98aa0d660e68e0)

**Comment by CrestApps** [comment]
I am not sure why are you adding the `_i()` into your views. Have you tried to use [accessor ](https://laravel.com/docs/5.4/eloquent-mutators#accessors-and-mutators) instead? I am not families with that package your using. But generally speaking, using assessor will give you many benefits. One that you won't have to add `_i()` method all over your project. Each time you access the property it will be automatically translated.


Regarding your first code, you may want to try the following instead and see if it'll work.
```
{{ isset({{modelHeader}}) ? _i({{modelHeader}}) : '{{modelName}}' }}
```

I may consider adding little more flexibility by making more variables available is the views. The template should be used to change the look and feel (HTML) not the entire code.

Let me know if the above code will work for you? Also, let me know the outcome after using accessors instead.

**Comment by essemme** [comment]
Well, i think the _i() function is mainly a presentation thing, so it reasonably belongs to the view - of course it's not mandatory, but as i'm already using it to show the translation of fixed text in the view, I prefer to keep them all in one place. 
But, you are right, in this case the pros of moving it to accessors (besides applying the function once vs potentially multiple times in the view) are even greater, it makes the view stubs a little bit simpler.
I'll check the model's stub and logic, and see if I can easily move these functions to accessors. 


Regarding this snippet: 
{{ isset({{modelHeader}}) ? _i({{modelHeader}}) : '{{modelName}}' }}
the problem was simply that the {{modelHeader}} label was not parsed for that stub file. 


Yes, I see that the custom template feature is meant to change the look and feel, and I agree, it wouldn't be wise to allow a complete overhaul of the views code and features.
Still, I find reasonable to allow some minor changes (like turning the table headers in the index view into sorting links), that could require some not yet available data in some stubs.  
I can easily add the logic (just one line) in the controller, not in the view because {{fieldName}} (available in index.view.stub) is not accessible in index.header.cell.blade.stub.
(so this change broke the resulting view:
`<th><a href="{!! Request::fullUrlWithQuery ( [ 'o' => '{{fieldName}}'] ) !!}"> {{ _i("{{fieldTitle}}") }} </a></th>`
)

Of course, as a simple user, I'm not in a position to know what's better for the package future development, so I'm just suggesting a deign option I'd personally find useful: would it be a good solution to just allow "subview" stubs access to the same contents of their "parents"? (or most od them)

**Comment by essemme** [comment]
Just tried (as follow up of #3 ) with the current dev-master code and my custom templates. 
All right, it seems I get all the content i need in every stub now.

(Kudos!)

**Comment by CrestApps** [comment]
Glad to know it is working for you.

**Comment by CrestApps** [comment]
To help make the templates easier to read and change, the variable schema of the template has been changed from `{{variableName}}` style to `[% variable_name %]` style.
