### ISSUE TITLE
match not working when using from database

### ISSUE THREAD

**Issue by nenads** [CrestApps/laravel-code-generator#80]
### Environment:
- Laravel-Code-Generator Version: 2.3.#
- Laravel Version: 5.6.#

### Steps/Commands To Reproduce:

Schema::create('tests', function(Blueprint $table)
        {
            $table->increments('id');
            $table->timestamps();
            $table->string('name', 255)->nullable();
            $table->string('file')->nullable();
            $table->string('image')->nullable();
            $table->string('picture')->nullable();

        });

php artisan resource-file:from-database Tests --table-name=tests --translation-for=en,sr --force

### Content Of The Resource-File:

`{
    "fields": [
        {
            "name": "id",
            "labels": {
                "en": "Id",
                "sr": "Id"
            },
            "html-type": "number",
            "css-class": "",
            "options": {},
            "html-value": null,
            "validation": "",
            "is-on-index": false,
            "is-on-show": false,
            "is-on-form": false,
            "data-type": "int",
            "data-type-params": [],
            "data-value": null,
            "is-index": false,
            "is-unique": false,
            "is-primary": true,
            "comment": null,
            "is-nullable": true,
            "is-header": false,
            "is-unsigned": true,
            "is-auto-increment": true,
            "is-inline-options": false,
            "is-date": false,
            "date-format": "",
            "cast-as": "",
            "placeholder": {
                "en": "Enter id here...",
                "sr": "Enter id here..."
            },
            "delimiter": "; ",
            "range": [],
            "foreign-relation": null,
            "foreign-constraint": null,
            "on-store": null,
            "on-update": null,
            "api-key": "id",
            "is-api-visible": true,
            "api-description": {
                "en": "The id of the model.",
                "sr": "The id of the model."
            }
        },
        {
            "name": "created_at",
            "labels": {
                "en": "Created At",
                "sr": "Created At"
            },
            "html-type": "text",
            "css-class": "",
            "options": {},
            "html-value": null,
            "validation": "",
            "is-on-index": false,
            "is-on-show": true,
            "is-on-form": false,
            "data-type": "timestamp",
            "data-type-params": [],
            "data-value": null,
            "is-index": false,
            "is-unique": false,
            "is-primary": false,
            "comment": null,
            "is-nullable": true,
            "is-header": false,
            "is-unsigned": false,
            "is-auto-increment": false,
            "is-inline-options": false,
            "is-date": false,
            "date-format": "j/n/Y g:i A",
            "cast-as": "",
            "placeholder": {
                "en": "Enter created at here...",
                "sr": "Enter created at here..."
            },
            "delimiter": "; ",
            "range": [],
            "foreign-relation": null,
            "foreign-constraint": null,
            "on-store": null,
            "on-update": null,
            "api-key": "created_at",
            "is-api-visible": false,
            "api-description": {
                "en": "The created at of the model.",
                "sr": "The created at of the model."
            }
        },
        {
            "name": "updated_at",
            "labels": {
                "en": "Updated At",
                "sr": "Updated At"
            },
            "html-type": "text",
            "css-class": "",
            "options": {},
            "html-value": null,
            "validation": "",
            "is-on-index": false,
            "is-on-show": true,
            "is-on-form": false,
            "data-type": "timestamp",
            "data-type-params": [],
            "data-value": null,
            "is-index": false,
            "is-unique": false,
            "is-primary": false,
            "comment": null,
            "is-nullable": true,
            "is-header": false,
            "is-unsigned": false,
            "is-auto-increment": false,
            "is-inline-options": false,
            "is-date": false,
            "date-format": "j/n/Y g:i A",
            "cast-as": "",
            "placeholder": {
                "en": "Enter updated at here...",
                "sr": "Enter updated at here..."
            },
            "delimiter": "; ",
            "range": [],
            "foreign-relation": null,
            "foreign-constraint": null,
            "on-store": null,
            "on-update": null,
            "api-key": "updated_at",
            "is-api-visible": false,
            "api-description": {
                "en": "The updated at of the model.",
                "sr": "The updated at of the model."
            }
        },
        {
            "name": "name",
            "labels": {
                "en": "Name",
                "sr": "Name"
            },
            "html-type": "text",
            "css-class": "",
            "options": {},
            "html-value": null,
            "validation": "nullable|string|min:0|max:255",
            "is-on-index": true,
            "is-on-show": true,
            "is-on-form": true,
            "data-type": "string",
            "data-type-params": [
                255
            ],
            "data-value": null,
            "is-index": false,
            "is-unique": false,
            "is-primary": false,
            "comment": null,
            "is-nullable": true,
            "is-header": true,
            "is-unsigned": false,
            "is-auto-increment": false,
            "is-inline-options": false,
            "is-date": false,
            "date-format": "",
            "cast-as": "",
            "placeholder": {
                "en": "Enter name here...",
                "sr": "Enter name here..."
            },
            "delimiter": "; ",
            "range": [],
            "foreign-relation": null,
            "foreign-constraint": null,
            "on-store": null,
            "on-update": null,
            "api-key": "name",
            "is-api-visible": true,
            "api-description": {
                "en": "The name of the model.",
                "sr": "The name of the model."
            }
        },
        {
            "name": "file",
            "labels": {
                "en": "File",
                "sr": "File"
            },
            "html-type": "text",
            "css-class": "",
            "options": {},
            "html-value": null,
            "validation": "nullable|file",
            "is-on-index": false,
            "is-on-show": true,
            "is-on-form": true,
            "data-type": "string",
            "data-type-params": [
                255
            ],
            "data-value": null,
            "is-index": false,
            "is-unique": false,
            "is-primary": false,
            "comment": null,
            "is-nullable": true,
            "is-header": false,
            "is-unsigned": false,
            "is-auto-increment": false,
            "is-inline-options": false,
            "is-date": false,
            "date-format": "",
            "cast-as": "",
            "placeholder": {},
            "delimiter": "; ",
            "range": [],
            "foreign-relation": null,
            "foreign-constraint": null,
            "on-store": null,
            "on-update": null,
            "api-key": "file",
            "is-api-visible": true,
            "api-description": {
                "en": "The file of the model.",
                "sr": "The file of the model."
            }
        },
        {
            "name": "image",
            "labels": {
                "en": "Image",
                "sr": "Image"
            },
            "html-type": "text",
            "css-class": "",
            "options": {},
            "html-value": null,
            "validation": "nullable|numeric",
            "is-on-index": true,
            "is-on-show": true,
            "is-on-form": true,
            "data-type": "string",
            "data-type-params": [
                255
            ],
            "data-value": null,
            "is-index": false,
            "is-unique": false,
            "is-primary": false,
            "comment": null,
            "is-nullable": true,
            "is-header": false,
            "is-unsigned": false,
            "is-auto-increment": false,
            "is-inline-options": false,
            "is-date": false,
            "date-format": "",
            "cast-as": "",
            "placeholder": {
                "en": "Enter image here...",
                "sr": "Enter image here..."
            },
            "delimiter": "; ",
            "range": [],
            "foreign-relation": null,
            "foreign-constraint": null,
            "on-store": null,
            "on-update": null,
            "api-key": "image",
            "is-api-visible": true,
            "api-description": {
                "en": "The image of the model.",
                "sr": "The image of the model."
            }
        },
        {
            "name": "picture",
            "labels": {
                "en": "Picture",
                "sr": "Picture"
            },
            "html-type": "text",
            "css-class": "",
            "options": {},
            "html-value": null,
            "validation": "nullable|file",
            "is-on-index": false,
            "is-on-show": true,
            "is-on-form": true,
            "data-type": "string",
            "data-type-params": [
                255
            ],
            "data-value": null,
            "is-index": false,
            "is-unique": false,
            "is-primary": false,
            "comment": null,
            "is-nullable": true,
            "is-header": false,
            "is-unsigned": false,
            "is-auto-increment": false,
            "is-inline-options": false,
            "is-date": false,
            "date-format": "",
            "cast-as": "",
            "placeholder": {},
            "delimiter": "; ",
            "range": [],
            "foreign-relation": null,
            "foreign-constraint": null,
            "on-store": null,
            "on-update": null,
            "api-key": "picture",
            "is-api-visible": true,
            "api-description": {
                "en": "The picture of the model.",
                "sr": "The picture of the model."
            }
        }
    ],
    "relations": [],
    "indexes": [],
    "auto-manage-created-and-updated-at": true,
    "table-name": "tests",
    "protection": {
        "is-model-protected": false,
        "is-controller-protected": false,
        "is-api-resource-protected": false,
        "is-api-resource-collection-protected": false,
        "is-api-documentation-protected": false,
        "is-api-documentation-controller-protected": false,
        "is-form-request-protected": false,
        "is-languages-protected": false,
        "is-form-view-protected": false,
        "is-index-view-protected": false,
        "is-create-view-protected": false,
        "is-edit-view-protected": false,
        "is-show-view-protected": false
    },
    "api-documentation": {
        "access_token_with_bearer": {
            "en": "The access token prefixed with the \"Bearer \" key word.",
            "sr": "The access token prefixed with the \"Bearer \" key word."
        },
        "index_route_description": {
            "en": "Retrieve existing tests.",
            "sr": "Retrieve existing tests."
        },
        "index_route_response_description": {
            "en": "The API's response will be JSON based data. The JSON object will be structured as follow",
            "sr": "The API's response will be JSON based data. The JSON object will be structured as follow"
        },
        "the_key_is_the_model_property_and_the_value_is_the_model_value": {
            "en": "The array's key is the tests property name where the value is the assigned value to the retrieved tests.",
            "sr": "The array's key is the tests property name where the value is the assigned value to the retrieved tests."
        },
        "link_to_retrieve_first_page": {
            "en": "Link to retrieve first page.",
            "sr": "Link to retrieve first page."
        },
        "link_to_retrieve_last_page": {
            "en": "Link to retrieve last page.",
            "sr": "Link to retrieve last page."
        },
        "link_to_retrieve_previous_page": {
            "en": "Link to retrieve previous page.",
            "sr": "Link to retrieve previous page."
        },
        "link_to_retrieve_next_page": {
            "en": "Link to retrieve next page.",
            "sr": "Link to retrieve next page."
        },
        "the_number_of_current_page": {
            "en": "The number of current page.",
            "sr": "The number of current page."
        },
        "the_index_of_the_first_retrieved_item": {
            "en": "The index of first retrieved tests.",
            "sr": "The index of first retrieved tests."
        },
        "the_number_of_the_last_page": {
            "en": "The number of the last page.",
            "sr": "The number of the last page."
        },
        "the_base_link_to_the_resource": {
            "en": "The base link to the api resource.",
            "sr": "The base link to the api resource."
        },
        "the_number_of_models_per_page": {
            "en": "The number of tests per page.",
            "sr": "The number of tests per page."
        },
        "the_index_of_the_last_retrieved_item": {
            "en": "The index of last retrieved tests.",
            "sr": "The index of last retrieved tests."
        },
        "the_total_of_available_pages": {
            "en": "The total of the available pages.",
            "sr": "The total of the available pages."
        },
        "store_route_description": {
            "en": "Create new tests.",
            "sr": "Create new tests."
        },
        "store_route_response_description": {
            "en": "The API's response will be JSON based data. The JSON object will be structured as follow",
            "sr": "The API's response will be JSON based data. The JSON object will be structured as follow"
        },
        "update_route_description": {
            "en": "Update existsing tests.",
            "sr": "Update existsing tests."
        },
        "update_route_response_description": {
            "en": "The API's response will be JSON based data. The JSON object will be structured as follow",
            "sr": "The API's response will be JSON based data. The JSON object will be structured as follow"
        },
        "show_route_description": {
            "en": "Retrieve existsing tests.",
            "sr": "Retrieve existsing tests."
        },
        "show_route_response_description": {
            "en": "The API's response will be JSON based data. The JSON object will be structured as follow",
            "sr": "The API's response will be JSON based data. The JSON object will be structured as follow"
        },
        "the_id_of_model_to_retrieve": {
            "en": "The unique id of the tests to retrieve",
            "sr": "The unique id of the tests to retrieve"
        },
        "destroy_route_description": {
            "en": "Delete existsing tests.",
            "sr": "Delete existsing tests."
        },
        "destroy_route_response_description": {
            "en": "The API's response will be JSON based data. The JSON object will be structured as follow",
            "sr": "The API's response will be JSON based data. The JSON object will be structured as follow"
        },
        "the_id_of_model_to_delete": {
            "en": "The id of the tests to delete.",
            "sr": "The id of the tests to delete."
        },
        "general_description": {
            "en": "Allows you to list, create, edit, show and delete tests.",
            "sr": "Allows you to list, create, edit, show and delete tests."
        },
        "indicate_whether_the_request_was_successful_or_not": {
            "en": "Indicate whether the request was successful or not.",
            "sr": "Indicate whether the request was successful or not."
        },
        "the_id_of_the_model": {
            "en": "The id of the tests.",
            "sr": "The id of the tests."
        },
        "this_parameter_must_be_present_in_the_request": {
            "en": "This parameter must be present in the request.",
            "sr": "This parameter must be present in the request."
        },
        "the_request_failed_validation": {
            "en": "The request failed validation.",
            "sr": "The request failed validation."
        },
        "list_of_the_invalid_errors": {
            "en": "List of the invalid errors.",
            "sr": "List of the invalid errors."
        },
        "the_requested_model_does_not_exists": {
            "en": "The requested tests does not exists.",
            "sr": "The requested tests does not exists."
        },
        "the_user_does_not_have_permission_to_access_the_requested_resource": {
            "en": "User does not have permission to access the requested resource.",
            "sr": "User does not have permission to access the requested resource."
        }
    }
}`

**Comment by nenads** [comment]
small not issue related question
can we have in json default upload location ? do we want all files to go to one folder.

"name": "picture",
            "labels": {
                "en": "Picture",
                "sr": "Picture"
            },
            "html-type": "file",
            "css-class": "",
            "options": {},

**Comment by CrestApps** [comment]
@nenads what is the issue here?

Regarding the json-default upload location question, I am not sure what you are trying to do. The package offer you a [setting ](https://github.com/CrestApps/laravel-code-generator/blob/master/config/codegenerator.php#L47-L58) to upload all your attachments.
