### ISSUE TITLE
How to update from v2.2 to v2.3-dev?

### ISSUE THREAD

**Issue by almiali** [CrestApps/laravel-code-generator#83]
hi 

I trying to update the files to     "crestapps/laravel-code-generator": "v2.3.x-dev",

i change composer file , also i run

 composer update
php artisan vendor:publish --provider="CrestApps\CodeGenerator\CodeGeneratorServiceProvider" --tag=default --force

when I run the second command, the message is: Publishing complete.

and files : codegenerator.php , codegenerator_custom.php  not updated,

is there anything missing?

thank you

**Comment by CrestApps** [comment]
with the dev version, you don't need to publish anything. Do the following 

1. Update the version in he composer.json file to `v2.3.x-dev`
2. Rename `codegenerator_custom.php` to `laravel-code-generator.php`
3. Remove the `codegenerator.php` file
4. Remove both `default` and `default-collective` folders found in `resources\laravel-code-generator\templates`

If you see any issues after that, please share with me the exact problem.
