### ISSUE TITLE
How to do multipleSelect with relationship from other table 

### ISSUE THREAD

**Issue by almi9** [CrestApps/laravel-code-generator#87]
Hi

how I can make multiple select that from another table by make relationship has many

I try to do it but I do not get any result 

I test that command

php artisan resource-file:create test --fields="id,name,is_active,name:colors;html-type:multipleSelect," --relations="name:Colors;type:hasMany;field:name;params:App\Models\Colors|colors|id,"

thank you

**Comment by CrestApps** [comment]
I Apologize for such a long delay in answer.

What you need here is to add a relation to the `foreign-relation` on the field like so

![image](https://user-images.githubusercontent.com/24724371/53697990-cbc5d800-3d8b-11e9-85e2-0c1e027c79e0.png)
