### ISSUE TITLE
Driver support for sqlsrv?

### ISSUE THREAD

**Issue by jenelso2** [CrestApps/laravel-code-generator#88]
- Laravel-Code-Generator Version: 2.2.7
- Laravel Version: 5.7

The documentation states that MySQL is the only supported driver right now, but I also noticed:

/src/DatabaseParsers/SqlServerParser.php

How close are you to having the sqlsrv driver supported?

Thanks,

-Jeremy

**Comment by CrestApps** [comment]
Hi, 
I have been slammed lately and have not had a chance to put the time in this package. If you have the time, making it SQL Server ready should not be much time.

If here like and have the time to make it SQL Server ready, here is your getting starting tips.
The MySQL Parser class is located at [MysqlParser.php](https://github.com/CrestApps/laravel-code-generator/blob/master/src/DatabaseParsers/MysqlParser.php)

The SQL Server class should be very similar to the MySQL class. The majority of the work if converting the MySQL queries which pull the definition of the columns/relation into SQL Server queries. Once that is done most of the work is done. 

Last step in to enable the SQL Server driver on line 48 [ResourceFileFromDatabaseCommand.php](https://github.com/CrestApps/laravel-code-generator/blob/master/src/Commands/ResourceFileFromDatabaseCommand.php#L48)

If you need help along the way, let me know and I'll be happy to help.
