### ISSUE TITLE
file name

### ISSUE THREAD

**Issue by almi9** [CrestApps/laravel-code-generator#93]
Hi

I have a question according to the file name

what is the method that you use to make sure that the name of the file will not duplicate?
did you use time() function?

**Comment by CrestApps** [comment]
Which file name are you referring too?

**Comment by almi9** [comment]
when I upload any file , that take  a long name , so is there any possibility to duplicate that name if i have more than 10000 files

**Comment by CrestApps** [comment]
We use php’s own uniqueid() method http://php.net/manual/en/function.uniqid.php

**Comment by almi9** [comment]
sorry but another question
what is the probability to duplicate the same name if I upload 1000000 images?

**Comment by CrestApps** [comment]
Did you read the documentation of how the uniqueid() function work? For the most part it generate a unique value. However it could fail in some cases. If you want to increase the chance of uniqueness you can change it to uniqueid(“”, true).   I hope your not planning on using this function to generate id for a database.
