### ISSUE TITLE
change upload path on FormRequest to other foulder

### ISSUE THREAD

**Issue by almi9** [CrestApps/laravel-code-generator#94]
Hi

is there any way to change the path on Form Request for one table only?

Also, another question, if I change the path of the uploaded file on the setting of "files_upload path" is the old files will affect?

And thank you for your support 💯

**Comment by CrestApps** [comment]
Well if the path is stored in the database as “uploads/name.extension” then in theory if you change the 'files_upload_path' setting to a new path then that won’t impact old files.

Try changing the setting and see if that breaks anything
