### ISSUE TITLE
Error on Creating Controller

### ISSUE THREAD

**Issue by SV-RAJA** [CrestApps/laravel-code-generator#96]
### Environment:
- Laravel-Code-Generator Version: #.#.#
- Laravel Version: #.#.#

**Comment by SV-RAJA** [comment]
php artisan create:controller Biography                                                                                                                                                                                                                                                                                                                                                            ErrorException  : compact(): Undefined variable: viewName                                                                                                                                                                                                                                                                                                                                        at E:\Projects\E-Commerce Live\vendor\crestapps\laravel-code-generator\src\Commands\CreateControllerCommand.php:398                                                                                394\|             'template',                                                                                                                                                                     395\|             'controllerName',                                                                                                                                                               396\|             'extends',                                                                                                                                                                      397\|             'withAuth',                                                                                                                                                                   > 398\|             'controllerDirectory'                                                                                                                                                           399\|         );                                                                                                                                                                                  400\|     }                                                                                                                                                                                       401\|                                                                                                                                                                                             402\|     /**                                                                                                                                                                                                                                                                                                                                                                                    Exception trace:                                                                                                                                                                                                                                                                                                                                                                                  1   compact("formRequestDirectory", "viewDirectory", "viewName", "modelName", "prefix", "perPage", "fileSnippet", "modelDirectory", "langFile", "fields", "withFormRequest", "formRequestName" , "force", "resourceFile", "template", "controllerName", "extends", "withAuth", "controllerDirectory")                                                                                                 E:\Projects\E-Commerce Live\vendor\crestapps\laravel-code-generator\src\Commands\CreateControllerCommand.php:398                                                                                                                                                                                                                                                                              2   CrestApps\CodeGenerator\Commands\CreateControllerCommand::getCommandInput()                                                                                                                      E:\Projects\E-Commerce Live\vendor\crestapps\laravel-code-generator\src\Commands\CreateControllerCommand.php:86                                                                                                                                                                                                                                                                               Please use the argument -v to see more details.
--

**Comment by CrestApps** [comment]
What version are tot using? 

What is the exact command that you called?

Please share the resource file and the generated code to help debugging the potential error

**Comment by SV-RAJA** [comment]
{
    "fields": [
        {
            "name": "id",
            "labels": "Id",
            "html-type": "text",
            "css-class": "",
            "options": {},
            "html-value": null,
            "validation": "",
            "is-on-index": false,
            "is-on-show": false,
            "is-on-form": false,
            "data-type": "int",
            "data-type-params": [],
            "data-value": null,
            "is-index": false,
            "is-unique": false,
            "is-primary": true,
            "comment": null,
            "is-nullable": true,
            "is-header": false,
            "is-unsigned": true,
            "is-auto-increment": true,
            "is-inline-options": false,
            "is-date": false,
            "date-format": "",
            "cast-as": "",
            "placeholder": "Enter id here...",
            "delimiter": "; ",
            "range": [],
            "foreign-relation": null,
            "foreign-constraint": null,
            "on-store": null,
            "on-update": null
        },
        {
            "name": "name",
            "labels": "Name",
            "html-type": "text",
            "css-class": "",
            "options": {},
            "html-value": null,
            "validation": "string|min:1|max:255",
            "is-on-index": true,
            "is-on-show": true,
            "is-on-form": true,
            "data-type": "string",
            "data-type-params": [
                255
            ],
            "data-value": null,
            "is-index": false,
            "is-unique": false,
            "is-primary": false,
            "comment": null,
            "is-nullable": true,
            "is-header": true,
            "is-unsigned": false,
            "is-auto-increment": false,
            "is-inline-options": false,
            "is-date": false,
            "date-format": "",
            "cast-as": "",
            "placeholder": "Enter name here...",
            "delimiter": "; ",
            "range": [],
            "foreign-relation": null,
            "foreign-constraint": null,
            "on-store": null,
            "on-update": null
        },
        {
            "name": "description",
            "labels": "Description",
            "html-type": "textarea",
            "css-class": "",
            "options": {},
            "html-value": null,
            "validation": "string|min:1|max:1000",
            "is-on-index": false,
            "is-on-show": true,
            "is-on-form": true,
            "data-type": "string",
            "data-type-params": [
                1000
            ],
            "data-value": null,
            "is-index": false,
            "is-unique": false,
            "is-primary": false,
            "comment": null,
            "is-nullable": true,
            "is-header": false,
            "is-unsigned": false,
            "is-auto-increment": false,
            "is-inline-options": false,
            "is-date": false,
            "date-format": "",
            "cast-as": "",
            "placeholder": {},
            "delimiter": "; ",
            "range": [],
            "foreign-relation": null,
            "foreign-constraint": null,
            "on-store": null,
            "on-update": null
        },
        {
            "name": "is_active",
            "labels": "Is Active",
            "html-type": "checkbox",
            "css-class": "",
            "options": {
                "0": "No",
                "1": "Yes"
            },
            "html-value": null,
            "validation": "boolean",
            "is-on-index": true,
            "is-on-show": true,
            "is-on-form": true,
            "data-type": "bool",
            "data-type-params": [],
            "data-value": null,
            "is-index": false,
            "is-unique": false,
            "is-primary": false,
            "comment": null,
            "is-nullable": true,
            "is-header": false,
            "is-unsigned": false,
            "is-auto-increment": false,
            "is-inline-options": false,
            "is-date": false,
            "date-format": "",
            "cast-as": "",
            "placeholder": {},
            "delimiter": "; ",
            "range": [],
            "foreign-relation": null,
            "foreign-constraint": null,
            "on-store": null,
            "on-update": null
        }
    ],
    "relations": [],
    "indexes": [],
    "auto-manage-created-and-updated-at": true,
    "table-name": null,
    "protection": {
        "is-model-protected": false,
        "is-controller-protected": false,
        "is-form-request-protected": false,
        "is-languages-protected": false,
        "is-form-view-protected": false,
        "is-index-view-protected": false,
        "is-create-view-protected": false,
        "is-edit-view-protected": false,
        "is-show-view-protected": false
    }
}

**Comment by SV-RAJA** [comment]
i have been using laravel 5.7
and about resource file created by

php artisan resource-file:create AssetCategory --fields=id,name,description,is_active

**Comment by SV-RAJA** [comment]
and then i have use command 
php artisan create:resources AssetCategory
